//! `config.toml` generator for telemt.
//!
//! Pure function: takes a `db::MtproxyInbound` + the runtime directory
//! and produces a TOML body the supervisor writes to
//! `<mtproxy_dir>/config.toml`. The supervisor restarts (or relies on
//! telemt's `notify`-based hot-reload) after every write.
//!
//! **We deliberately do not write `[access.users]`.** Telemt's HTTP API
//! at `127.0.0.1:9091/v1/users` is the authoritative path for user
//! CRUD; coffeeblack-vpn reconciles `mtproxy_users_table` into it via
//! `client.rs` after every supervisor spawn. Writing users into
//! config.toml as well would create a second source of truth and a
//! merge problem on restart.

use anyhow::{anyhow, Result};
use std::fmt::Write as _;
use std::path::Path;

use crate::db::MtproxyInbound;

/// Build the `config.toml` body for the given inbound. The runtime
/// directory is used both for the `tls_front_dir` cache (real TLS
/// records telemt fetches from `tls_domain` to mimic) and as the parent
/// of the PID file (the supervisor passes `--pid-file` separately).
///
/// Validation: refuses obviously-broken combinations (no modes
/// enabled, port out of range, `modes_tls` enabled with empty
/// `tls_domain`, `ad_tag` of the wrong length). Server-side validation
/// is duplicated in `api/mtproxy.rs` so bad PUTs return 4xx, but doing
/// it here too means the supervisor never spawns telemt with an
/// obviously-broken file.
pub fn generate(inbound: &MtproxyInbound, mtproxy_dir: &Path) -> Result<String> {
    validate(inbound)?;

    let mut body = String::new();
    writeln!(body, "# Generated by coffeeblack-vpn — do NOT edit by hand.").unwrap();
    writeln!(
        body,
        "# Per-user secrets live in mtproxy_users_table and are pushed"
    )
    .unwrap();
    writeln!(
        body,
        "# into telemt via 127.0.0.1:9091/v1/users on every spawn —"
    )
    .unwrap();
    writeln!(
        body,
        "# that is why this file has no per-user access section."
    )
    .unwrap();
    body.push('\n');

    writeln!(body, "[general]").unwrap();
    writeln!(
        body,
        "use_middle_proxy = {}",
        bool_lit(inbound.use_middle_proxy)
    )
    .unwrap();
    if !inbound.ad_tag.trim().is_empty() {
        writeln!(body, "ad_tag = {}", toml_string(&inbound.ad_tag)).unwrap();
    }
    writeln!(body, "log_level = \"normal\"").unwrap();
    body.push('\n');

    writeln!(body, "[general.modes]").unwrap();
    writeln!(body, "classic = {}", bool_lit(inbound.modes_classic)).unwrap();
    writeln!(body, "secure  = {}", bool_lit(inbound.modes_secure)).unwrap();
    writeln!(body, "tls     = {}", bool_lit(inbound.modes_tls)).unwrap();
    body.push('\n');

    writeln!(body, "[general.links]").unwrap();
    // `show = "*"` lets every user's links appear in the [server.api]
    // user-detail responses. We render every user's links via the API,
    // so this stays "*" — operators who want to hide links from the
    // admin UI flip the `enabled` field on the user instead.
    writeln!(body, "show = \"*\"").unwrap();
    if !inbound.public_host.trim().is_empty() {
        writeln!(body, "public_host = {}", toml_string(&inbound.public_host)).unwrap();
    }
    if inbound.public_port > 0 {
        writeln!(body, "public_port = {}", inbound.public_port).unwrap();
    }
    body.push('\n');

    writeln!(body, "[server]").unwrap();
    writeln!(body, "port = {}", inbound.port).unwrap();
    body.push('\n');

    // [server.api] — the runtime control plane coffeeblack-vpn proxies user
    // CRUD through. Locked to loopback + tight whitelist so this is
    // never reachable from outside the host: operator auth happens at
    // /api/admin/mtproxy/* in the coffeeblack-vpn router.
    writeln!(body, "[server.api]").unwrap();
    writeln!(body, "enabled = true").unwrap();
    writeln!(body, "listen = \"127.0.0.1:9091\"").unwrap();
    writeln!(body, "whitelist = [\"127.0.0.1/32\", \"::1/128\"]").unwrap();
    body.push('\n');

    // [[server.listeners]] — bind 0.0.0.0 so v4 clients reach the proxy.
    // v6 listeners can be added by appending another [[server.listeners]]
    // table via additional_config; the default is intentionally minimal.
    writeln!(body, "[[server.listeners]]").unwrap();
    writeln!(body, "ip = \"0.0.0.0\"").unwrap();
    body.push('\n');

    // [censorship] — Fake-TLS / SNI-fronting parameters. Required by
    // modes_tls=true; harmless when only classic/secure are on (the
    // tls_emulation knob just builds an unused cache).
    writeln!(body, "[censorship]").unwrap();
    writeln!(body, "tls_domain = {}", toml_string(&inbound.tls_domain)).unwrap();
    writeln!(body, "mask = {}", bool_lit(inbound.mask_enabled)).unwrap();
    writeln!(body, "tls_emulation = true").unwrap();
    let tls_front = mtproxy_dir.join("tlsfront");
    writeln!(
        body,
        "tls_front_dir = {}",
        toml_string(&tls_front.to_string_lossy())
    )
    .unwrap();
    body.push('\n');

    // Empty [access] block — telemt requires the section to exist even
    // when users are managed via the API. The API can populate users at
    // runtime without the section pre-existing, but having it on disk
    // means cold starts (before the reconciler hits) are valid TOML.
    writeln!(body, "[access]").unwrap();
    body.push('\n');

    // Verbatim escape hatch. Operators paste advanced bits the UI
    // doesn't model — extra listeners, metrics_port, censorship
    // tweaks. We don't validate the appended block; if it's invalid,
    // telemt rejects the file at start time.
    let extra = inbound.additional_config.trim();
    if !extra.is_empty() {
        writeln!(body, "# --- operator additional_config (verbatim) ---").unwrap();
        body.push_str(extra);
        if !body.ends_with('\n') {
            body.push('\n');
        }
    }

    Ok(body)
}

/// Validate the inbound for "could telemt actually run with this?".
/// Cheap structural checks only — DNS reachability of `tls_domain`,
/// MTProto-protocol-level details, etc. are telemt's job.
pub fn validate(inbound: &MtproxyInbound) -> Result<()> {
    if inbound.port < 1 || inbound.port > 65535 {
        return Err(anyhow!(
            "MTProxy port must be 1..=65535, got {}",
            inbound.port
        ));
    }
    if inbound.public_port != 0 && (inbound.public_port < 1 || inbound.public_port > 65535) {
        return Err(anyhow!(
            "MTProxy public_port must be 0 (= use port) or 1..=65535, got {}",
            inbound.public_port
        ));
    }
    if !inbound.modes_classic && !inbound.modes_secure && !inbound.modes_tls {
        return Err(anyhow!(
            "MTProxy inbound has no modes enabled — at least one of \
             modes_classic / modes_secure / modes_tls must be true"
        ));
    }
    if inbound.modes_tls && inbound.tls_domain.trim().is_empty() {
        return Err(anyhow!(
            "MTProxy modes_tls=true requires a non-empty tls_domain"
        ));
    }
    if !inbound.ad_tag.trim().is_empty() {
        validate_hex32("ad_tag", &inbound.ad_tag)?;
    }
    // tls_domain syntax — basic sanity. Telemt itself fetches the cert
    // at startup so a bogus domain crashes at run-time anyway, but we
    // reject obviously-empty / whitespace-only values here.
    let dom = inbound.tls_domain.trim();
    if !dom.is_empty()
        && (dom.contains(' ') || dom.contains('\t') || dom.starts_with('.') || dom.ends_with('.'))
    {
        return Err(anyhow!(
            "MTProxy tls_domain {dom:?} doesn't look like a hostname"
        ));
    }
    Ok(())
}

/// Validate that `value` is exactly 32 lowercase-hex characters — the
/// standard MTProxy secret / ad_tag format from @MTProxybot.
pub fn validate_hex32(field: &str, value: &str) -> Result<()> {
    let v = value.trim();
    if v.len() != 32 || !v.chars().all(|c| c.is_ascii_hexdigit()) {
        return Err(anyhow!(
            "{field} must be exactly 32 hex characters (got {} chars)",
            v.len()
        ));
    }
    Ok(())
}

fn bool_lit(b: bool) -> &'static str {
    if b {
        "true"
    } else {
        "false"
    }
}

/// Render a Rust string as a TOML basic string literal. Escapes the
/// characters TOML requires escaped (backslash + double quote + ASCII
/// control). Adequate for the values we emit — hostnames, hex strings,
/// filesystem paths under our control.
fn toml_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04X}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn fixture() -> MtproxyInbound {
        MtproxyInbound {
            id: "mtproxy0".into(),
            port: 8080,
            public_host: String::new(),
            public_port: 0,
            tls_domain: "petrovich.ru".into(),
            mask_enabled: true,
            modes_classic: false,
            modes_secure: false,
            modes_tls: true,
            use_middle_proxy: true,
            ad_tag: String::new(),
            additional_config: String::new(),
            enabled: true,
            created_at: "n".into(),
            updated_at: "n".into(),
        }
    }

    #[test]
    fn fake_tls_only_minimal_config() {
        let toml = generate(&fixture(), &PathBuf::from("/tmp/coffeeblack-mtproxy"))
            .expect("generate succeeds");
        // Top-level sections present.
        assert!(toml.contains("[general]"));
        assert!(toml.contains("[general.modes]"));
        assert!(toml.contains("[general.links]"));
        assert!(toml.contains("[server]"));
        assert!(toml.contains("[server.api]"));
        assert!(toml.contains("[[server.listeners]]"));
        assert!(toml.contains("[censorship]"));
        assert!(toml.contains("[access]"));

        // Mode wiring.
        assert!(toml.contains("classic = false"));
        assert!(toml.contains("secure  = false"));
        assert!(toml.contains("tls     = true"));

        // Port + tls_domain.
        assert!(toml.contains("port = 8080"));
        assert!(toml.contains("tls_domain = \"petrovich.ru\""));

        // No ad_tag / public_host / public_port — those are omitted
        // when their stored value is the empty / zero default.
        assert!(!toml.contains("ad_tag ="));
        assert!(!toml.contains("public_host"));
        assert!(!toml.contains("public_port"));

        // tls_front_dir lives under mtproxy_dir.
        assert!(toml.contains("tls_front_dir = \"/tmp/coffeeblack-mtproxy/tlsfront\""));

        // No [access.users] — the contract.
        assert!(!toml.contains("[access.users]"));
    }

    #[test]
    fn populated_optional_fields_render() {
        let mut inbound = fixture();
        inbound.public_host = "proxy.example.com".into();
        inbound.public_port = 443;
        inbound.ad_tag = "0123456789abcdef0123456789abcdef".into();
        inbound.modes_classic = true;
        inbound.modes_secure = true;
        let toml = generate(&inbound, &PathBuf::from("/srv/mtproxy")).unwrap();
        assert!(toml.contains("public_host = \"proxy.example.com\""));
        assert!(toml.contains("public_port = 443"));
        assert!(toml.contains("ad_tag = \"0123456789abcdef0123456789abcdef\""));
        assert!(toml.contains("classic = true"));
        assert!(toml.contains("secure  = true"));
    }

    #[test]
    fn additional_config_appended_verbatim() {
        let mut inbound = fixture();
        inbound.additional_config = "[server]\nmetrics_port = 9090\n".into();
        let toml = generate(&inbound, &PathBuf::from("/tmp/x")).unwrap();
        assert!(toml.ends_with("metrics_port = 9090\n"));
        assert!(toml.contains("# --- operator additional_config (verbatim) ---"));
    }

    #[test]
    fn rejects_no_modes_enabled() {
        let mut inbound = fixture();
        inbound.modes_tls = false;
        let err = generate(&inbound, &PathBuf::from("/tmp/x")).unwrap_err();
        assert!(err.to_string().contains("no modes enabled"));
    }

    #[test]
    fn rejects_tls_with_empty_domain() {
        let mut inbound = fixture();
        inbound.tls_domain = String::new();
        let err = generate(&inbound, &PathBuf::from("/tmp/x")).unwrap_err();
        assert!(err.to_string().contains("tls_domain"));
    }

    #[test]
    fn rejects_bad_ad_tag_length() {
        let mut inbound = fixture();
        inbound.ad_tag = "deadbeef".into();
        let err = generate(&inbound, &PathBuf::from("/tmp/x")).unwrap_err();
        assert!(err.to_string().contains("32 hex"));
    }

    #[test]
    fn rejects_bad_port() {
        let mut inbound = fixture();
        inbound.port = 0;
        let err = generate(&inbound, &PathBuf::from("/tmp/x")).unwrap_err();
        assert!(err.to_string().contains("port"));
    }

    #[test]
    fn toml_escapes_quotes_and_backslashes() {
        // Path with awkward characters — make sure the renderer emits a
        // syntactically valid TOML basic string. Real life: a Windows
        // path or someone naming their dir with a quote in it.
        let mut inbound = fixture();
        inbound.public_host = "ev\"il\\host".into();
        let toml = generate(&inbound, &PathBuf::from("/tmp/x")).unwrap();
        assert!(toml.contains("public_host = \"ev\\\"il\\\\host\""));
    }

    #[test]
    fn validate_hex32_accepts_lowercase() {
        validate_hex32("x", "0123456789abcdef0123456789abcdef").unwrap();
    }

    #[test]
    fn validate_hex32_rejects_uppercase_or_short() {
        // We accept any-case hex — the hex digit set is mixed-case
        // tolerant per char::is_ascii_hexdigit. The spec requires
        // length 32; that's what we enforce.
        validate_hex32("x", "0123456789ABCDEF0123456789ABCDEF").unwrap();
        assert!(validate_hex32("x", "deadbeef").is_err());
        assert!(validate_hex32("x", "Z123456789abcdef0123456789abcdef").is_err());
    }
}
