//! AmneziaWG configuration file generation.
//!
//! Pure AmneziaWG — all configs use `awg`-compatible format with
//! obfuscation parameters.

use crate::db;
use anyhow::Result;

fn parse_json_arr(s: &str) -> Vec<String> {
    serde_json::from_str(s).unwrap_or_default()
}

fn server_ip(cidr: &str) -> String {
    if let Ok(net) = cidr.parse::<ipnet::Ipv4Net>() {
        // `checked_add` guards the (pathological) all-ones base address so a
        // debug build can't panic on overflow; wrap is fine on the max edge.
        let ip = std::net::Ipv4Addr::from(u32::from(net.addr()).wrapping_add(1));
        return format!("{}/{}", ip, net.prefix_len());
    }
    if let Ok(net) = cidr.parse::<ipnet::Ipv6Net>() {
        let ip = std::net::Ipv6Addr::from(u128::from(net.addr()).wrapping_add(1));
        return format!("{}/{}", ip, net.prefix_len());
    }
    cidr.to_string()
}

fn sanitize_for_shell(s: &str) -> String {
    s.chars()
        .filter(|c| c.is_alphanumeric() || matches!(c, '.' | '-' | '_' | '/' | ':'))
        .collect()
}

fn expand(template: &str, device: &str, port: &str, v4: &str, v6: &str) -> String {
    template
        .replace("{{device}}", &sanitize_for_shell(device))
        .replace("{{port}}", &sanitize_for_shell(port))
        .replace("{{ipv4Cidr}}", &sanitize_for_shell(v4))
        .replace("{{ipv6Cidr}}", &sanitize_for_shell(v6))
}

/// Render the AmneziaWG 3 `[Interface]` lines for this device.
///
/// Shared by the server and client config paths so the two ends can never
/// disagree about a value that has to match (`HeaderProtectionKey`) or that
/// upstream recommends setting on both (`ContentPaddingAddition`). Emits
/// nothing at all when no AWG 3 knob is set, which is the default — an
/// upgraded deployment renders byte-identical configs until an operator
/// turns one on.
fn awg3_lines(iface: &db::Interface) -> Vec<String> {
    crate::wg::awg3::config_lines(
        &iface.header_protection_key,
        &[
            ("ContentPaddingAddition", &iface.content_padding_addition),
            ("RekeyAfterTime", &iface.rekey_after_time),
            ("RekeyTimeout", &iface.rekey_timeout),
            ("RejectAfterTime", &iface.reject_after_time),
            ("KeepaliveTimeout", &iface.keepalive_timeout),
            ("MaxHandshakeAttempts", &iface.max_handshake_attempts),
        ],
        iface.random_trailers,
        iface.disable_cookies,
    )
}

/// Generate server [Interface] section.
pub fn generate_server_interface(iface: &db::Interface, hooks: &db::Hooks) -> Result<String> {
    let port = iface.port.to_string();
    let v4 = server_ip(&iface.ipv4_cidr);
    let v6 = server_ip(&iface.ipv6_cidr);
    let addr = if crate::config::CONFIG.disable_ipv6 {
        v4.clone()
    } else {
        format!("{}, {}", v4, v6)
    };

    let mut awg = vec![
        format!("Jc = {}", iface.j_c),
        format!("Jmin = {}", iface.j_min),
        format!("Jmax = {}", iface.j_max),
        format!("S1 = {}", iface.s1),
        format!("S2 = {}", iface.s2),
    ];
    if let Some(v) = iface.s3 { if v > 0 { awg.push(format!("S3 = {}", v)); } }
    if let Some(v) = iface.s4 { if v > 0 { awg.push(format!("S4 = {}", v)); } }
    if !iface.h1.is_empty() { awg.push(format!("H1 = {}", iface.h1)); }
    if !iface.h2.is_empty() { awg.push(format!("H2 = {}", iface.h2)); }
    if !iface.h3.is_empty() { awg.push(format!("H3 = {}", iface.h3)); }
    if !iface.h4.is_empty() { awg.push(format!("H4 = {}", iface.h4)); }
    if !iface.i1.is_empty() { awg.push(format!("I1 = {}", iface.i1)); }
    if !iface.i2.is_empty() { awg.push(format!("I2 = {}", iface.i2)); }
    if !iface.i3.is_empty() { awg.push(format!("I3 = {}", iface.i3)); }
    if !iface.i4.is_empty() { awg.push(format!("I4 = {}", iface.i4)); }
    if !iface.i5.is_empty() { awg.push(format!("I5 = {}", iface.i5)); }
    awg.extend(awg3_lines(iface));

    // Free-form append (mirrors amnezia-client's additionalServerConfig).
    // Lives at the bottom of the [Interface] block, just before [Peer]s
    // are appended by sync_to_disk(). The trailing newline keeps the
    // section boundary clean even when this is empty.
    let extra = iface.additional_config.trim();
    let extra_block = if extra.is_empty() {
        String::new()
    } else {
        format!("\n{}", extra)
    };

    Ok(format!(
        "# Note: Do not edit this file directly.\n\
         # Your changes will be overwritten!\n\n\
         # Server\n\
         [Interface]\n\
         PrivateKey = {pk}\n\
         Address = {addr}\n\
         ListenPort = {port}\n\
         MTU = {mtu}\n\
         {awg}\n\
         PreUp = {pre_up}\n\
         PostUp = {post_up}\n\
         PreDown = {pre_down}\n\
         PostDown = {post_down}{extra}",
        pk = iface.private_key,
        addr = addr,
        port = iface.port,
        mtu = iface.mtu,
        awg = awg.join("\n"),
        pre_up = expand(&hooks.pre_up, &iface.device, &port, &iface.ipv4_cidr, &iface.ipv6_cidr),
        post_up = expand(&hooks.post_up, &iface.device, &port, &iface.ipv4_cidr, &iface.ipv6_cidr),
        pre_down = expand(&hooks.pre_down, &iface.device, &port, &iface.ipv4_cidr, &iface.ipv6_cidr),
        post_down = expand(&hooks.post_down, &iface.device, &port, &iface.ipv4_cidr, &iface.ipv6_cidr),
        extra = extra_block,
    ))
}

/// Generate a [Peer] section for an enabled client.
pub fn generate_server_peer(client: &db::Client) -> Result<String> {
    let ipv4 = client.ipv4_address.as_deref().unwrap_or("0.0.0.0");
    let ipv6 = client.ipv6_address.as_deref().unwrap_or("::");
    let psk = client.pre_shared_key.as_deref().unwrap_or("");

    let mut allowed = vec![format!("{}/32", ipv4)];
    if !crate::config::CONFIG.disable_ipv6 {
        allowed.push(format!("{}/128", ipv6));
    }
    if let Some(ref sai) = client.server_allowed_ips {
        allowed.extend(parse_json_arr(sai));
    }

    let mut extra = String::new();
    if let Some(ref ep) = client.server_endpoint {
        if !ep.is_empty() {
            extra.push_str(&format!("\nEndpoint = {}", ep));
        }
    }
    // Per-peer AmneziaWG opt-in. When set, awg-tools forwards the value to
    // the kernel's WGPEER_A_ADVANCED_SECURITY netlink attribute. When
    // unset, the kernel auto-detects from the H1 magic header on the first
    // incoming handshake (noise.c:601-633).
    if let Some(adv) = client.advanced_security {
        extra.push_str(&format!(
            "\nAdvancedSecurity = {}",
            if adv { "on" } else { "off" }
        ));
    }

    let safe_name = client.name.replace(['\n', '\r'], " ");

    Ok(format!(
        "# Client: {name} ({id})\n\
         [Peer]\n\
         PublicKey = {pubkey}\n\
         PresharedKey = {psk}\n\
         AllowedIPs = {allowed}{extra}",
        name = safe_name,
        id = client.id,
        pubkey = client.public_key,
        psk = psk,
        allowed = allowed.join(", "),
        extra = extra,
    ))
}

/// Generate a complete client .conf file.
pub fn generate_client_config(
    iface: &db::Interface,
    user_config: &db::UserConfig,
    client: &db::Client,
) -> Result<String> {
    let ipv4 = client.ipv4_address.as_deref().unwrap_or("0.0.0.0");
    let ipv6 = client.ipv6_address.as_deref().unwrap_or("::");
    let psk = client.pre_shared_key.as_deref().unwrap_or("");

    let addr = if crate::config::CONFIG.disable_ipv6 {
        format!("{}/32", ipv4)
    } else {
        format!("{}/32, {}/128", ipv4, ipv6)
    };

    // DNS: client > user_config default
    let dns_list = match client.dns.as_deref() {
        Some(s) if !s.is_empty() => parse_json_arr(s),
        _ => parse_json_arr(&user_config.default_dns),
    };
    let dns_line = if dns_list.is_empty() {
        String::new()
    } else {
        format!("\nDNS = {}", dns_list.join(", "))
    };

    // AllowedIPs: client > user_config default
    let allowed_list = match client.allowed_ips.as_deref() {
        Some(s) if !s.is_empty() => parse_json_arr(s),
        _ => parse_json_arr(&user_config.default_allowed_ips),
    };

    // Hooks
    let mut hooks = Vec::new();
    if let Some(ref s) = client.pre_up { if !s.is_empty() { hooks.push(format!("PreUp = {}", s)); } }
    if let Some(ref s) = client.post_up { if !s.is_empty() { hooks.push(format!("PostUp = {}", s)); } }
    if let Some(ref s) = client.pre_down { if !s.is_empty() { hooks.push(format!("PreDown = {}", s)); } }
    if let Some(ref s) = client.post_down { if !s.is_empty() { hooks.push(format!("PostDown = {}", s)); } }

    // AWG params
    let jc = client.j_c.unwrap_or(iface.j_c);
    let jmin = client.j_min.unwrap_or(iface.j_min);
    let jmax = client.j_max.unwrap_or(iface.j_max);

    let mut awg = vec![
        format!("Jc = {}", jc),
        format!("Jmin = {}", jmin),
        format!("Jmax = {}", jmax),
        format!("S1 = {}", iface.s1),
        format!("S2 = {}", iface.s2),
    ];
    if let Some(v) = iface.s3 { if v > 0 { awg.push(format!("S3 = {}", v)); } }
    if let Some(v) = iface.s4 { if v > 0 { awg.push(format!("S4 = {}", v)); } }
    if !iface.h1.is_empty() { awg.push(format!("H1 = {}", iface.h1)); }
    if !iface.h2.is_empty() { awg.push(format!("H2 = {}", iface.h2)); }
    if !iface.h3.is_empty() { awg.push(format!("H3 = {}", iface.h3)); }
    if !iface.h4.is_empty() { awg.push(format!("H4 = {}", iface.h4)); }

    if let Some(ref s) = client.i1 { if !s.is_empty() { awg.push(format!("I1 = {}", s)); } }
    if let Some(ref s) = client.i2 { if !s.is_empty() { awg.push(format!("I2 = {}", s)); } }
    if let Some(ref s) = client.i3 { if !s.is_empty() { awg.push(format!("I3 = {}", s)); } }
    if let Some(ref s) = client.i4 { if !s.is_empty() { awg.push(format!("I4 = {}", s)); } }
    if let Some(ref s) = client.i5 { if !s.is_empty() { awg.push(format!("I5 = {}", s)); } }
    // AWG 3 device knobs are rendered from the interface for the client too.
    // `HeaderProtectionKey` has to match on both ends or nothing decrypts;
    // `ContentPaddingAddition` is documented as best set on both; and the
    // timers are the operator's intent for the tunnel as a whole, so a peer
    // that silently kept protocol defaults would drift from the server's
    // rekey schedule. There is no per-client override for any of them.
    awg.extend(awg3_lines(iface));
    // J1/J2/J3/Itime intentionally not emitted — see note in
    // generate_server_interface() above.

    // From the client's perspective the [Peer] block represents the
    // server. We're a pure-AmneziaWG deployment, so the client should
    // always treat the server as advanced. If the operator explicitly set
    // a tri-state value on the client row we honour it; otherwise default
    // to `on` (mirrors the server's effective behaviour).
    let adv_line = match client.advanced_security {
        Some(true) => "\nAdvancedSecurity = on",
        Some(false) => "\nAdvancedSecurity = off",
        None => "\nAdvancedSecurity = on",
    };

    // Free-form [Interface] append (mirrors amnezia-client's
    // additionalClientConfig). Per-client override > UserConfig default.
    let extra_raw = match client.additional_config.as_deref() {
        Some(s) if !s.trim().is_empty() => s.trim(),
        _ => user_config.default_additional_config.trim(),
    };
    let extra_iface = if extra_raw.is_empty() {
        String::new()
    } else {
        format!("\n{}", extra_raw)
    };

    Ok(format!(
        "[Interface]\n\
         PrivateKey = {privkey}\n\
         Address = {addr}\n\
         MTU = {mtu}{dns}\n\
         {hooks}\
         {awg}{extra_iface}\n\
         [Peer]\n\
         PublicKey = {srv_pubkey}\n\
         PresharedKey = {psk}\n\
         AllowedIPs = {allowed}\n\
         PersistentKeepalive = {ka}\n\
         Endpoint = {host}:{port}{adv}",
        privkey = client.private_key,
        addr = addr,
        mtu = client.mtu,
        dns = dns_line,
        hooks = if hooks.is_empty() { String::new() } else { format!("{}\n", hooks.join("\n")) },
        awg = awg.join("\n"),
        extra_iface = extra_iface,
        srv_pubkey = iface.public_key,
        psk = psk,
        allowed = allowed_list.join(", "),
        ka = client.persistent_keepalive,
        host = user_config.host,
        port = user_config.port,
        adv = adv_line,
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db;

    fn iface_fixture() -> db::Interface {
        db::Interface {
            name: "awg0".into(),
            device: "eth0".into(),
            port: 51820,
            private_key: "SRV_PRIV".into(),
            public_key: "SRV_PUB".into(),
            ipv4_cidr: "10.8.0.0/24".into(),
            ipv6_cidr: "fdcc::cafe:0/112".into(),
            mtu: 1420,
            j_c: 7, j_min: 10, j_max: 1000,
            s1: 128, s2: 56, s3: None, s4: None,
            h1: "5-100".into(), h2: "200-300".into(),
            h3: "400-500".into(), h4: "600-700".into(),
            i1: String::new(), i2: String::new(), i3: String::new(),
            i4: String::new(), i5: String::new(),
            header_protection_key: String::new(),
            content_padding_addition: String::new(),
            rekey_after_time: String::new(),
            rekey_timeout: String::new(),
            reject_after_time: String::new(),
            keepalive_timeout: String::new(),
            max_handshake_attempts: String::new(),
            random_trailers: false,
            disable_cookies: false,
            firewall_enabled: false,
            dns_lockdown: false,
            dns_lockdown_target: String::new(),
            dns_block_external: true,
            additional_config: String::new(),
            enabled: true,
            created_at: "now".into(),
            updated_at: "now".into(),
        }
    }

    fn hooks_fixture() -> db::Hooks {
        db::Hooks {
            id: "awg0".into(),
            pre_up: String::new(),
            post_up: String::new(),
            pre_down: String::new(),
            post_down: String::new(),
            created_at: "now".into(),
            updated_at: "now".into(),
        }
    }

    fn user_config_fixture() -> db::UserConfig {
        db::UserConfig {
            id: "awg0".into(),
            default_mtu: 1420,
            default_persistent_keepalive: 25,
            default_dns: r#"["1.1.1.1"]"#.into(),
            default_allowed_ips: r#"["0.0.0.0/0"]"#.into(),
            default_j_c: 7, default_j_min: 10, default_j_max: 1000,
            default_i1: String::new(), default_i2: String::new(),
            default_i3: String::new(), default_i4: String::new(),
            default_i5: String::new(),
            default_additional_config: String::new(),
            host: "vpn.example.com".into(),
            port: 51820,
        }
    }

    fn client_fixture() -> db::Client {
        db::Client {
            id: 1,
            user_id: None,
            interface_id: Some("awg0".into()),
            name: "alice".into(),
            ipv4_address: Some("10.8.0.2".into()),
            ipv6_address: Some("fdcc::cafe:2".into()),
            private_key: "CLI_PRIV".into(),
            public_key: "CLI_PUB".into(),
            pre_shared_key: Some("PSK".into()),
            pre_up: None, post_up: None, pre_down: None, post_down: None,
            expires_at: None,
            allowed_ips: None,
            server_allowed_ips: None,
            firewall_ips: None,
            persistent_keepalive: 25,
            mtu: 1420,
            j_c: None, j_min: None, j_max: None,
            i1: None, i2: None, i3: None, i4: None, i5: None,
            dns: None,
            server_endpoint: None,
            advanced_security: None,
            additional_config: None,
            enabled: true,
            created_at: "now".into(),
            updated_at: "now".into(),
        }
    }

    #[test]
    fn server_interface_omits_additional_config_when_empty() {
        let cfg = generate_server_interface(&iface_fixture(), &hooks_fixture()).unwrap();
        // No trailing dangling line should appear.
        assert!(cfg.contains("PostDown ="));
        // No accidental empty-line leak from the append logic.
        assert!(!cfg.ends_with("\n\n"));
        assert!(!cfg.contains("Table = off"));
    }

    #[test]
    fn server_interface_appends_additional_config_verbatim() {
        let mut iface = iface_fixture();
        iface.additional_config = "Table = off\nFwMark = 0xca6c".into();
        let cfg = generate_server_interface(&iface, &hooks_fixture()).unwrap();
        assert!(cfg.contains("Table = off"));
        assert!(cfg.contains("FwMark = 0xca6c"));
        // Append must come after the hook lines.
        let postdown_idx = cfg.find("PostDown =").unwrap();
        let table_idx = cfg.find("Table = off").unwrap();
        assert!(table_idx > postdown_idx);
    }

    // ---- AmneziaWG 3 -----------------------------------------------------

    /// Set every AWG 3 knob on a fixture, with S1-S4 legal for header
    /// protection.
    fn awg3_iface() -> db::Interface {
        let mut i = iface_fixture();
        i.s3 = Some(20);
        i.s4 = Some(20);
        i.header_protection_key = "aGVhZGVyLXByb3RlY3Rpb24ta2V5LTMyLWJ5dGVzISE=".into();
        i.content_padding_addition = "10-40".into();
        i.rekey_after_time = "90".into();
        i.rekey_timeout = "5".into();
        i.reject_after_time = "180".into();
        i.keepalive_timeout = "25".into();
        i.max_handshake_attempts = "18".into();
        i.random_trailers = true;
        i.disable_cookies = true;
        i
    }

    #[test]
    fn awg3_emits_nothing_when_unset() {
        // The default fixture has no AWG 3 field set — the whole feature has
        // to be invisible in the rendered config, or every existing
        // deployment's wire format changes on upgrade.
        let conf =
            generate_server_interface(&iface_fixture(), &hooks_fixture()).unwrap();
        for key in [
            "HeaderProtectionKey",
            "ContentPaddingAddition",
            "RekeyAfterTime",
            "RekeyTimeout",
            "RejectAfterTime",
            "KeepaliveTimeout",
            "MaxHandshakeAttempts",
            "RandomTrailers",
            "DisableCookies",
        ] {
            assert!(!conf.contains(key), "{key} leaked into a default config:\n{conf}");
        }
        let client = generate_client_config(
            &iface_fixture(),
            &user_config_fixture(),
            &client_fixture(),
        )
        .unwrap();
        assert!(!client.contains("HeaderProtectionKey"));
        assert!(!client.contains("RandomTrailers"));
    }

    #[test]
    fn awg3_server_config_renders_every_set_knob() {
        let conf = generate_server_interface(&awg3_iface(), &hooks_fixture()).unwrap();
        for line in [
            "HeaderProtectionKey = aGVhZGVyLXByb3RlY3Rpb24ta2V5LTMyLWJ5dGVzISE=",
            "ContentPaddingAddition = 10-40",
            "RekeyAfterTime = 90",
            "RekeyTimeout = 5",
            "RejectAfterTime = 180",
            "KeepaliveTimeout = 25",
            "MaxHandshakeAttempts = 18",
            "RandomTrailers = on",
            "DisableCookies = on",
        ] {
            assert!(conf.contains(line), "missing {line:?} in:\n{conf}");
        }
        // AWG 3 lines belong in [Interface], before the hooks and the
        // free-form append — not stranded after a [Peer] header.
        let hpk = conf.find("HeaderProtectionKey").unwrap();
        assert!(hpk > conf.find("[Interface]").unwrap());
        assert!(hpk < conf.find("PreUp").unwrap());
    }

    #[test]
    fn awg3_client_config_carries_the_same_device_values() {
        // HeaderProtectionKey has to match on both ends or nothing
        // decrypts, so a client config that omitted it would hand the
        // operator a peer that silently never connects.
        let conf = generate_client_config(
            &awg3_iface(),
            &user_config_fixture(),
            &client_fixture(),
        )
        .unwrap();
        for line in [
            "HeaderProtectionKey = aGVhZGVyLXByb3RlY3Rpb24ta2V5LTMyLWJ5dGVzISE=",
            "ContentPaddingAddition = 10-40",
            "RekeyAfterTime = 90",
            "RandomTrailers = on",
            "DisableCookies = on",
        ] {
            assert!(conf.contains(line), "missing {line:?} in:\n{conf}");
        }
        // Still inside the client's own [Interface], not the [Peer] block
        // that describes the server.
        let hpk = conf.find("HeaderProtectionKey").unwrap();
        assert!(hpk < conf.find("[Peer]").unwrap(), "AWG 3 lines must precede [Peer]");
    }

    #[test]
    fn awg3_off_switches_render_no_line_at_all() {
        // `RandomTrailers = off` is the device default. Emitting it would
        // change nothing on AWG 3 and abort interface bring-up on AWG 2,
        // so an off switch has to be silent rather than explicit.
        let mut i = awg3_iface();
        i.random_trailers = false;
        i.disable_cookies = false;
        let conf = generate_server_interface(&i, &hooks_fixture()).unwrap();
        assert!(!conf.contains("RandomTrailers"));
        assert!(!conf.contains("DisableCookies"));
        assert!(conf.contains("HeaderProtectionKey"), "other knobs still render");
    }

    #[test]
    fn client_config_falls_back_to_user_config_default() {
        let mut uc = user_config_fixture();
        uc.default_additional_config = "Table = off".into();
        let cfg = generate_client_config(&iface_fixture(), &uc, &client_fixture()).unwrap();
        // Append must land inside the [Interface] block, before [Peer].
        let iface_idx = cfg.find("[Interface]").unwrap();
        let peer_idx = cfg.find("[Peer]").unwrap();
        let extra_idx = cfg.find("Table = off").unwrap();
        assert!(extra_idx > iface_idx && extra_idx < peer_idx);
    }

    #[test]
    fn client_config_per_peer_override_wins() {
        let mut uc = user_config_fixture();
        uc.default_additional_config = "FromDefault = yes".into();
        let mut client = client_fixture();
        client.additional_config = Some("FromPeer = yes".into());
        let cfg = generate_client_config(&iface_fixture(), &uc, &client).unwrap();
        assert!(cfg.contains("FromPeer = yes"));
        assert!(!cfg.contains("FromDefault = yes"));
    }

    #[test]
    fn client_config_empty_override_falls_through_to_default() {
        let mut uc = user_config_fixture();
        uc.default_additional_config = "FromDefault = yes".into();
        let mut client = client_fixture();
        // Whitespace-only counts as "not set" so an admin can clear the
        // textarea on the edit page without losing the global default.
        client.additional_config = Some("   ".into());
        let cfg = generate_client_config(&iface_fixture(), &uc, &client).unwrap();
        assert!(cfg.contains("FromDefault = yes"));
    }

    #[test]
    fn client_config_omits_block_when_both_empty() {
        let cfg = generate_client_config(&iface_fixture(), &user_config_fixture(), &client_fixture()).unwrap();
        // No spurious blank lines or stray fragments.
        assert!(!cfg.contains("FromDefault"));
        assert!(!cfg.contains("FromPeer"));
        // [Peer] must follow [Interface] directly with one blank-line break.
        let peer_idx = cfg.find("[Peer]").unwrap();
        let advsec_idx = cfg.find("AdvancedSecurity = on").unwrap();
        assert!(advsec_idx > peer_idx, "AdvancedSecurity belongs to [Peer], not [Interface]");
    }
}
