//! `bundle.zip` — one download that is a working mdnsvpn client.
//!
//! ## Why a bundle at all
//!
//! A peer needs *two* files, not one. The resolver list is only ever read from
//! `client_resolvers.txt` (see `share`'s module docs for the exact lookup
//! rules), and a missing file is a fatal startup error rather than a fallback.
//! Handing out a config alone — or a base64 share blob, which cannot carry the
//! list at all — produces a client that dies with
//! `resolver file not found: …/client_resolvers.txt`.
//!
//! The bundle puts both files in one archive, with the resolver file named
//! exactly what the client looks for, plus a launcher and a README so the
//! failure mode never comes up.
//!
//! ## Why a hand-rolled ZIP
//!
//! ZIP is the format that opens with a double-click on every desktop OS a peer
//! might use. Writing one with **stored** (uncompressed) entries needs only
//! CRC-32 and two fixed-layout records, so we get it without adding a
//! dependency to a tree that deliberately froze and pruned its dependency set
//! (`deny.toml`). Config bundles are a few KB; compression would save nothing
//! worth a supply-chain entry.
//!
//! Deliberate simplifications, all safe for our fixed, self-generated inputs:
//! stored-only (no deflate), no Zip64 (entries are KB), no data descriptors,
//! and a fixed DOS timestamp (see `DOS_DATE_TIME`).

use std::fmt::Write as _;

use crate::db::{MdnsvpnClient, MdnsvpnInbound};
use crate::mdnsvpn::share::{self, ShareBundle, CONFIG_FILENAME, RESOLVERS_FILENAME};

/// Fixed modification stamp: 1980-01-01 00:00:00, the DOS epoch and the lowest
/// value the format can express.
///
/// A real timestamp would make the archive bytes depend on wall-clock time,
/// which costs reproducibility (identical inputs should give identical output,
/// which is what lets the tests assert on bytes) and buys a peer nothing.
/// Packed as `(date << 16) | time`.
const DOS_DATE_TIME: u32 = 0x0021_0000;

/// One file inside the archive.
struct Entry {
    name: &'static str,
    /// Unix mode for the external attributes field. Launchers need +x.
    mode: u32,
    data: Vec<u8>,
}

/// Assemble the peer's bundle. Returns the raw `.zip` bytes.
pub fn build(inbound: &MdnsvpnInbound, client: &MdnsvpnClient) -> anyhow::Result<Vec<u8>> {
    let rendered = share::render_bundle(inbound, client)?;
    Ok(build_from_bundle(client, &rendered))
}

fn build_from_bundle(client: &MdnsvpnClient, rendered: &ShareBundle) -> Vec<u8> {
    let entries = vec![
        Entry {
            name: CONFIG_FILENAME,
            mode: 0o600,
            data: rendered.config_toml.clone().into_bytes(),
        },
        Entry {
            name: RESOLVERS_FILENAME,
            mode: 0o644,
            data: rendered.resolvers_txt.clone().into_bytes(),
        },
        Entry {
            name: "README.txt",
            mode: 0o644,
            data: render_readme(client, rendered).into_bytes(),
        },
        Entry {
            name: "run.sh",
            mode: 0o755,
            data: render_launcher_sh().into_bytes(),
        },
        Entry {
            name: "run.cmd",
            mode: 0o644,
            data: render_launcher_cmd().into_bytes(),
        },
    ];
    write_zip(&entries)
}

/// Plain-text instructions. Deliberately states the resolver requirement and
/// the exact error a peer sees when it is not met, because that error names a
/// file rather than the cause.
fn render_readme(client: &MdnsvpnClient, rendered: &ShareBundle) -> String {
    let safe_name: String = client.name.chars().filter(|c| !c.is_control()).collect();
    let mut out = String::new();

    writeln!(out, "mdnsvpn client bundle for \"{safe_name}\"").unwrap();
    writeln!(out, "Generated by awg-easy-rs.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "CONTENTS").unwrap();
    writeln!(out, "  {CONFIG_FILENAME}     tunnel settings + encryption key").unwrap();
    writeln!(
        out,
        "  {RESOLVERS_FILENAME}   DNS resolvers to tunnel through (REQUIRED)"
    )
    .unwrap();
    writeln!(out, "  run.sh / run.cmd          launcher for Linux+macOS / Windows").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "RUN IT").unwrap();
    writeln!(
        out,
        "  1. Put the mdnsvpn client binary in this folder (or on your PATH)."
    )
    .unwrap();
    writeln!(out, "  2. Linux/macOS:  ./run.sh").unwrap();
    writeln!(out, "     Windows:      run.cmd").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "  Or by hand, from inside this folder:").unwrap();
    writeln!(
        out,
        "     mdnsvpn -config {CONFIG_FILENAME} -resolvers {RESOLVERS_FILENAME}"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "  Then point your browser or app at the SOCKS5 proxy on"
    )
    .unwrap();
    writeln!(out, "  127.0.0.1:{}.", client.listen_port).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "KEEP BOTH FILES TOGETHER").unwrap();
    writeln!(
        out,
        "  mdnsvpn reads the resolver list only from a file — never from"
    )
    .unwrap();
    writeln!(
        out,
        "  {CONFIG_FILENAME}. If {RESOLVERS_FILENAME} is missing, startup"
    )
    .unwrap();
    writeln!(out, "  fails outright with:").unwrap();
    writeln!(out, "     resolver file not found: .../{RESOLVERS_FILENAME}").unwrap();
    writeln!(
        out,
        "  That is why this is a bundle and not a single config file."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "RESOLVERS IN THIS BUNDLE ({})", rendered.resolvers.len()).unwrap();
    for r in &rendered.resolvers {
        writeln!(out, "  {r}").unwrap();
    }
    writeln!(out).unwrap();
    writeln!(out, "KEEP THIS PRIVATE").unwrap();
    writeln!(
        out,
        "  {CONFIG_FILENAME} contains the tunnel's shared encryption key."
    )
    .unwrap();
    writeln!(
        out,
        "  Every peer on this server shares that one key, so leaking it"
    )
    .unwrap();
    writeln!(out, "  compromises everyone, not just you.").unwrap();

    out
}

/// POSIX launcher. `cd`s to its own directory so the relative paths hold
/// wherever the peer unzipped the bundle, and prefers a co-located binary over
/// one on `PATH`.
fn render_launcher_sh() -> String {
    let mut out = String::new();
    writeln!(out, "#!/bin/sh").unwrap();
    writeln!(out, "# Generated by awg-easy-rs. Launches the mdnsvpn client").unwrap();
    writeln!(out, "# with this bundle's config and resolver list.").unwrap();
    writeln!(out, "set -eu").unwrap();
    writeln!(out, "cd \"$(dirname \"$0\")\"").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "BIN=./mdnsvpn").unwrap();
    writeln!(out, "if [ ! -x \"$BIN\" ]; then").unwrap();
    writeln!(out, "  BIN=$(command -v mdnsvpn || true)").unwrap();
    writeln!(out, "fi").unwrap();
    writeln!(out, "if [ -z \"$BIN\" ]; then").unwrap();
    writeln!(
        out,
        "  echo \"mdnsvpn client binary not found — put it in this folder or on PATH\" >&2"
    )
    .unwrap();
    writeln!(out, "  exit 1").unwrap();
    writeln!(out, "fi").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "exec \"$BIN\" -config {CONFIG_FILENAME} -resolvers {RESOLVERS_FILENAME} \"$@\""
    )
    .unwrap();
    out
}

/// Windows launcher. CRLF line endings — `cmd.exe` mis-parses a bare-LF batch
/// file (it splits on CR, so LF-only lines run together).
fn render_launcher_cmd() -> String {
    let lines = [
        "@echo off",
        "REM Generated by awg-easy-rs. Launches the mdnsvpn client",
        "REM with this bundle's config and resolver list.",
        "cd /d \"%~dp0\"",
        "",
        "set BIN=mdnsvpn.exe",
        "if not exist \"%BIN%\" set BIN=mdnsvpn",
        "",
        &format!("\"%BIN%\" -config {CONFIG_FILENAME} -resolvers {RESOLVERS_FILENAME} %*"),
        "if errorlevel 1 pause",
    ];
    let mut out = String::new();
    for line in lines {
        out.push_str(line);
        out.push_str("\r\n");
    }
    out
}

// ---------------------------------------------------------------------------
// Minimal stored-entry ZIP writer
// ---------------------------------------------------------------------------

fn write_zip(entries: &[Entry]) -> Vec<u8> {
    let mut out = Vec::new();
    // (local-header offset, crc32, size) per entry, for the central directory.
    let mut placed: Vec<(u32, u32, u32)> = Vec::with_capacity(entries.len());

    for entry in entries {
        let offset = out.len() as u32;
        let crc = crc32(&entry.data);
        let size = entry.data.len() as u32;

        // Local file header (PK\x03\x04).
        out.extend_from_slice(b"PK\x03\x04");
        push_u16(&mut out, 10); // version needed: 1.0 (stored)
        push_u16(&mut out, 0); // flags
        push_u16(&mut out, 0); // method: stored
        push_u32(&mut out, DOS_DATE_TIME);
        push_u32(&mut out, crc);
        push_u32(&mut out, size); // compressed size == size (stored)
        push_u32(&mut out, size);
        push_u16(&mut out, entry.name.len() as u16);
        push_u16(&mut out, 0); // extra field length
        out.extend_from_slice(entry.name.as_bytes());
        out.extend_from_slice(&entry.data);

        placed.push((offset, crc, size));
    }

    let central_start = out.len() as u32;
    for (entry, &(offset, crc, size)) in entries.iter().zip(placed.iter()) {
        // Central directory header (PK\x01\x02).
        out.extend_from_slice(b"PK\x01\x02");
        // "Version made by": 3 (Unix) << 8 | 20, which is what tells the
        // extractor to honour the Unix mode in the external attributes below.
        // Without the Unix host byte, run.sh loses its +x bit.
        push_u16(&mut out, (3 << 8) | 20);
        push_u16(&mut out, 10); // version needed
        push_u16(&mut out, 0); // flags
        push_u16(&mut out, 0); // method: stored
        push_u32(&mut out, DOS_DATE_TIME);
        push_u32(&mut out, crc);
        push_u32(&mut out, size);
        push_u32(&mut out, size);
        push_u16(&mut out, entry.name.len() as u16);
        push_u16(&mut out, 0); // extra
        push_u16(&mut out, 0); // comment
        push_u16(&mut out, 0); // disk number start
        push_u16(&mut out, 0); // internal attributes
        // External attributes: Unix mode in the high 16 bits, with the regular
        // -file type bits (0o100000) so extractors do not read it as a device.
        push_u32(&mut out, ((0o100000 | entry.mode) & 0xFFFF) << 16);
        push_u32(&mut out, offset);
        out.extend_from_slice(entry.name.as_bytes());
    }
    let central_size = out.len() as u32 - central_start;

    // End of central directory (PK\x05\x06).
    out.extend_from_slice(b"PK\x05\x06");
    push_u16(&mut out, 0); // this disk
    push_u16(&mut out, 0); // disk with central dir
    push_u16(&mut out, entries.len() as u16);
    push_u16(&mut out, entries.len() as u16);
    push_u32(&mut out, central_size);
    push_u32(&mut out, central_start);
    push_u16(&mut out, 0); // comment length

    out
}

fn push_u16(out: &mut Vec<u8>, v: u16) {
    out.extend_from_slice(&v.to_le_bytes());
}

fn push_u32(out: &mut Vec<u8>, v: u32) {
    out.extend_from_slice(&v.to_le_bytes());
}

/// CRC-32/ISO-HDLC (the "IEEE" variant ZIP uses), computed bitwise so there is
/// no table to get wrong. Bundles are kilobytes; this is not a hot path.
fn crc32(data: &[u8]) -> u32 {
    let mut crc = 0xFFFF_FFFFu32;
    for &byte in data {
        crc ^= byte as u32;
        for _ in 0..8 {
            let mask = (crc & 1).wrapping_neg();
            crc = (crc >> 1) ^ (0xEDB8_8320 & mask);
        }
    }
    !crc
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_inbound() -> MdnsvpnInbound {
        MdnsvpnInbound {
            id: "mdnsvpn0".into(),
            domains: r#"["v.example.com"]"#.into(),
            port: 53,
            bind: "0.0.0.0".into(),
            encryption_method: 5,
            encryption_key: "deadbeefcafebabe1234567890abcdef".into(),
            protocol_type: "SOCKS5".into(),
            dns_upstream_servers: r#"["1.1.1.1:53"]"#.into(),
            forward_ip: String::new(),
            forward_port: 0,
            use_external_socks5: false,
            socks5_auth: false,
            socks5_user: String::new(),
            socks5_pass: String::new(),
            additional_config: String::new(),
            enabled: true,
            created_at: "now".into(),
            updated_at: "now".into(),
        }
    }

    fn fixture_client() -> MdnsvpnClient {
        MdnsvpnClient {
            id: 1,
            user_id: None,
            inbound_id: "mdnsvpn0".into(),
            name: "alice".into(),
            resolvers: String::new(),
            listen_port: 18000,
            socks5_user: String::new(),
            socks5_pass: String::new(),
            expires_at: None,
            additional_config_toml: None,
            enabled: true,
            created_at: "now".into(),
            updated_at: "now".into(),
        }
    }

    /// Known-answer test for the CRC — a wrong CRC produces an archive that
    /// looks fine until an extractor rejects it.
    #[test]
    fn crc32_matches_the_standard_check_value() {
        assert_eq!(crc32(b"123456789"), 0xCBF4_3926);
        assert_eq!(crc32(b""), 0);
        assert_eq!(crc32(b"a"), 0xE8B7_BE43);
    }

    #[test]
    fn archive_has_zip_magic_and_terminator() {
        let zip = build(&fixture_inbound(), &fixture_client()).unwrap();
        assert!(zip.starts_with(b"PK\x03\x04"), "no local header magic");
        assert!(
            zip.windows(4).any(|w| w == b"PK\x05\x06"),
            "no end-of-central-directory record"
        );
    }

    /// The whole point of the bundle: the resolver file must be present under
    /// the exact name the client looks for.
    #[test]
    fn archive_contains_every_file_a_peer_needs() {
        let zip = build(&fixture_inbound(), &fixture_client()).unwrap();
        let names = entry_names(&zip);
        assert!(names.contains(&CONFIG_FILENAME.to_string()), "{names:?}");
        assert!(names.contains(&RESOLVERS_FILENAME.to_string()), "{names:?}");
        assert!(names.contains(&"README.txt".to_string()), "{names:?}");
        assert!(names.contains(&"run.sh".to_string()), "{names:?}");
        assert!(names.contains(&"run.cmd".to_string()), "{names:?}");
    }

    #[test]
    fn central_directory_entry_count_matches_local_headers() {
        let zip = build(&fixture_inbound(), &fixture_client()).unwrap();
        let locals = count_occurrences(&zip, b"PK\x03\x04");
        let centrals = count_occurrences(&zip, b"PK\x01\x02");
        assert_eq!(locals, 5);
        assert_eq!(centrals, 5);
    }

    /// Stored entries mean file contents appear verbatim, so we can assert the
    /// payloads landed without implementing an unzipper.
    #[test]
    fn stored_entries_embed_content_verbatim() {
        let inbound = fixture_inbound();
        let client = fixture_client();
        let rendered = share::render_bundle(&inbound, &client).unwrap();
        let zip = build(&inbound, &client).unwrap();
        let blob = String::from_utf8_lossy(&zip);

        assert!(blob.contains(&rendered.config_toml));
        assert!(blob.contains(&rendered.resolvers_txt));
        // And the key really is in there — this archive is secret-bearing.
        assert!(blob.contains("deadbeefcafebabe1234567890abcdef"));
    }

    #[test]
    fn readme_states_the_resolver_requirement_and_the_proxy_port() {
        let zip = build(&fixture_inbound(), &fixture_client()).unwrap();
        let blob = String::from_utf8_lossy(&zip);
        assert!(blob.contains("resolver file not found"));
        assert!(blob.contains("127.0.0.1:18000"));
        assert!(blob.contains("8.8.8.8"), "resolver list not listed in README");
    }

    #[test]
    fn launchers_pass_both_paths_to_the_client() {
        let sh = render_launcher_sh();
        assert!(sh.contains(&format!("-config {CONFIG_FILENAME}")));
        assert!(sh.contains(&format!("-resolvers {RESOLVERS_FILENAME}")));
        // Must survive being unzipped anywhere.
        assert!(sh.contains("cd \"$(dirname \"$0\")\""));

        let cmd = render_launcher_cmd();
        assert!(cmd.contains(&format!("-config {CONFIG_FILENAME}")));
        assert!(cmd.contains(&format!("-resolvers {RESOLVERS_FILENAME}")));
        assert!(cmd.contains("cd /d \"%~dp0\""));
        // cmd.exe needs CRLF, and no line may be left with a bare LF.
        assert!(cmd.contains("\r\n"));
        assert!(!cmd.replace("\r\n", "").contains('\n'));
    }

    #[test]
    fn run_sh_is_marked_executable_in_the_archive() {
        let zip = build(&fixture_inbound(), &fixture_client()).unwrap();
        let mode = external_mode_for(&zip, "run.sh").expect("run.sh in central directory");
        assert_eq!(mode & 0o111, 0o111, "run.sh not executable: {mode:o}");
        let cfg_mode =
            external_mode_for(&zip, CONFIG_FILENAME).expect("config in central directory");
        assert_eq!(cfg_mode & 0o777, 0o600, "config not owner-only: {cfg_mode:o}");
    }

    /// Same inputs must give the same bytes — otherwise the assertions above
    /// are testing a moving target, and callers cannot cache or checksum.
    #[test]
    fn output_is_deterministic() {
        let a = build(&fixture_inbound(), &fixture_client()).unwrap();
        let b = build(&fixture_inbound(), &fixture_client()).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn per_client_resolver_override_reaches_the_archive() {
        let mut client = fixture_client();
        client.resolvers = r#"["10.10.10.10"]"#.into();
        let zip = build(&fixture_inbound(), &client).unwrap();
        let blob = String::from_utf8_lossy(&zip);
        assert!(blob.contains("10.10.10.10"));
        // The curated baseline must not leak in when overridden.
        let payload_lines: Vec<&str> = blob
            .lines()
            .filter(|l| !l.trim_start().starts_with('#'))
            .collect();
        assert!(!payload_lines.join("\n").contains("8.8.8.8"));
    }

    #[test]
    fn missing_domains_is_an_error_not_a_broken_archive() {
        let mut inbound = fixture_inbound();
        inbound.domains = "[]".into();
        assert!(build(&inbound, &fixture_client()).is_err());
    }

    // -- helpers ---------------------------------------------------------

    fn count_occurrences(haystack: &[u8], needle: &[u8]) -> usize {
        haystack.windows(needle.len()).filter(|w| *w == needle).count()
    }

    /// Walk the central directory and collect entry names.
    fn entry_names(zip: &[u8]) -> Vec<String> {
        let mut names = Vec::new();
        let mut i = 0usize;
        while i + 46 <= zip.len() {
            if &zip[i..i + 4] != b"PK\x01\x02" {
                i += 1;
                continue;
            }
            let name_len = u16::from_le_bytes([zip[i + 28], zip[i + 29]]) as usize;
            let start = i + 46;
            if start + name_len > zip.len() {
                break;
            }
            names.push(String::from_utf8_lossy(&zip[start..start + name_len]).to_string());
            i = start + name_len;
        }
        names
    }

    /// Unix mode from a central-directory entry's external attributes.
    fn external_mode_for(zip: &[u8], want: &str) -> Option<u32> {
        let mut i = 0usize;
        while i + 46 <= zip.len() {
            if &zip[i..i + 4] != b"PK\x01\x02" {
                i += 1;
                continue;
            }
            let name_len = u16::from_le_bytes([zip[i + 28], zip[i + 29]]) as usize;
            let attrs = u32::from_le_bytes([zip[i + 38], zip[i + 39], zip[i + 40], zip[i + 41]]);
            let start = i + 46;
            if start + name_len > zip.len() {
                return None;
            }
            let name = String::from_utf8_lossy(&zip[start..start + name_len]);
            if name == want {
                return Some(attrs >> 16);
            }
            i = start + name_len;
        }
        None
    }
}
