//! `server_config.toml` generator for MasterDnsVPN.
//!
//! Pure function: takes a `db::MdnsvpnInbound` + the runtime directory
//! and produces a TOML body the supervisor writes to
//! `<mdnsvpn_dir>/server_config.toml`. The supervisor restarts mdnsvpn
//! after every config change — the upstream binary doesn't expose a
//! SIGHUP / `notify`-style hot-reload that we can rely on, so re-spawn
//! is the safe path.
//!
//! Validation: refuses obviously-broken combinations (no domains, port
//! out of range, illegal encryption method, TCP-mode without a forward
//! target, etc.). Server-side validation is duplicated in
//! `api/mdnsvpn.rs` so bad PUTs return 4xx, but doing it here too means
//! the supervisor never spawns mdnsvpn with an obviously-broken file.

use std::fmt::Write as _;
use std::path::Path;

use anyhow::{anyhow, Result};

use crate::db::MdnsvpnInbound;
use crate::mdnsvpn::keys;

/// Filename mdnsvpn reads the shared key from. Lives next to
/// `server_config.toml` under `mdnsvpn_dir`.
pub const KEY_FILENAME: &str = "encrypt_key.txt";

/// Per-session ceiling on concurrent tunnel streams, i.e. on the outbound TCP
/// connections one peer's session can make this node hold open.
///
/// Upstream defaults `MAX_ALLOWED_CLIENT_ACTIVE_STREAMS_PER_SESSION` to 2000
/// and applies it per session, so the shipped posture lets a single session
/// pin 2000 sockets. 256 leaves ample headroom for real browsing while
/// bounding single-peer resource exhaustion.
pub const MAX_STREAMS_PER_SESSION: u32 = 256;

/// Build the `server_config.toml` body for the given inbound. The
/// runtime directory is used as the parent of the key file
/// (`encrypt_key.txt`).
pub fn generate(inbound: &MdnsvpnInbound, mdnsvpn_dir: &Path) -> Result<String> {
    validate(inbound)?;

    let domains: Vec<String> = parse_json_string_array(&inbound.domains)
        .map_err(|e| anyhow!("MasterDnsVPN domains: {e}"))?;
    if domains.is_empty() {
        return Err(anyhow!(
            "MasterDnsVPN inbound has no `domains` — set at least one NS-delegated FQDN"
        ));
    }
    let upstreams: Vec<String> = parse_json_string_array(&inbound.dns_upstream_servers)
        .map_err(|e| anyhow!("MasterDnsVPN dns_upstream_servers: {e}"))?;

    // Read once, up front: the generated sections below consult it so we never
    // emit a key the operator has already set (TOML rejects duplicates).
    let extra_config = inbound.additional_config.trim();

    let mut body = String::new();
    writeln!(body, "# Generated by coffeeblack-vpn — do NOT edit by hand.").unwrap();
    writeln!(body, "# Bumped on every admin save; manual edits are overwritten.").unwrap();
    body.push('\n');

    // ------------------------------------------------------------------
    // 1) Tunnel policy
    // ------------------------------------------------------------------
    writeln!(body, "DOMAIN = {}", toml_string_array(&domains)).unwrap();
    writeln!(body, "PROTOCOL_TYPE = {}", toml_string(&inbound.protocol_type)).unwrap();
    body.push('\n');

    // Default to upstream's "everything is allowed" compression set.
    // Operators tweak via `additional_config` if they need to lock it
    // down.
    writeln!(body, "SUPPORTED_UPLOAD_COMPRESSION_TYPES = [0, 1, 2, 3]").unwrap();
    writeln!(body, "SUPPORTED_DOWNLOAD_COMPRESSION_TYPES = [0, 1, 2, 3]").unwrap();
    body.push('\n');

    // ------------------------------------------------------------------
    // 2) UDP listener
    // ------------------------------------------------------------------
    writeln!(body, "UDP_HOST = {}", toml_string(&inbound.bind)).unwrap();
    writeln!(body, "UDP_PORT = {}", inbound.port).unwrap();
    body.push('\n');

    // ------------------------------------------------------------------
    // 5) DNS tunnel upstream
    // ------------------------------------------------------------------
    if !upstreams.is_empty() {
        writeln!(
            body,
            "DNS_UPSTREAM_SERVERS = {}",
            toml_string_array(&upstreams)
        )
        .unwrap();
    }
    body.push('\n');

    // ------------------------------------------------------------------
    // 6) Upstream SOCKS / forwarding
    // ------------------------------------------------------------------
    writeln!(
        body,
        "USE_EXTERNAL_SOCKS5 = {}",
        bool_lit(inbound.use_external_socks5)
    )
    .unwrap();
    writeln!(body, "SOCKS5_AUTH = {}", bool_lit(inbound.socks5_auth)).unwrap();
    if inbound.socks5_auth {
        writeln!(body, "SOCKS5_USER = {}", toml_string(&inbound.socks5_user)).unwrap();
        writeln!(body, "SOCKS5_PASS = {}", toml_string(&inbound.socks5_pass)).unwrap();
    }
    writeln!(body, "FORWARD_IP = {}", toml_string(&inbound.forward_ip)).unwrap();
    writeln!(body, "FORWARD_PORT = {}", inbound.forward_port).unwrap();
    body.push('\n');

    // ------------------------------------------------------------------
    // 7) Security
    // ------------------------------------------------------------------
    writeln!(
        body,
        "DATA_ENCRYPTION_METHOD = {}",
        inbound.encryption_method
    )
    .unwrap();
    let key_path = mdnsvpn_dir.join(KEY_FILENAME);
    writeln!(
        body,
        "ENCRYPTION_KEY_FILE = {}",
        toml_string(&key_path.to_string_lossy())
    )
    .unwrap();
    if !keys::is_aead(inbound.encryption_method) {
        // Not fatal — an operator may deliberately want method 0 for
        // debugging, and refusing to start would be worse than warning. But
        // it must be loud in both the rendered file and our log stream.
        writeln!(
            body,
            "# WARNING: {} ({}) is NOT authenticated encryption. An active",
            inbound.encryption_method,
            keys::method_name(inbound.encryption_method)
        )
        .unwrap();
        writeln!(
            body,
            "# on-path attacker can tamper with tunnel payloads undetected."
        )
        .unwrap();
        writeln!(
            body,
            "# Use DATA_ENCRYPTION_METHOD = {} (AES-256-GCM) unless you have a",
            keys::RECOMMENDED_ENCRYPTION_METHOD
        )
        .unwrap();
        writeln!(
            body,
            "# specific reason not to. Changing it requires re-issuing every"
        )
        .unwrap();
        writeln!(body, "# client config (the method is baked into each one).").unwrap();
        crate::warn!(
            method = inbound.encryption_method,
            method_name = keys::method_name(inbound.encryption_method),
            recommended = keys::RECOMMENDED_ENCRYPTION_METHOD,
            "MasterDnsVPN is configured with a non-AEAD cipher — tunnel payloads \
             are not integrity-protected against an active on-path attacker"
        );
    }
    body.push('\n');

    // ------------------------------------------------------------------
    // 8) Resource ceilings
    // ------------------------------------------------------------------
    // Upstream's own ceilings are already bounded for everything a client
    // negotiates (duplication counts, MTUs, batch sizes, ARQ window), so we
    // deliberately leave those at their defaults rather than second-guess
    // them. The one outlier is the per-session stream cap: upstream defaults
    // `MAX_ALLOWED_CLIENT_ACTIVE_STREAMS_PER_SESSION` to 2000, and that value
    // is applied per session (`sessionRecord.MaxActiveStreamsPerSession`,
    // enforced in `internal/udpserver/session.go`). One peer holding a single
    // session can therefore ask this node to hold 2000 concurrent outbound
    // TCP connections. 256 is generous for real traffic (a browser uses
    // dozens) and bounds what any one peer can consume.
    //
    // Operators who genuinely need more set it in `additional_config`; we then
    // skip our own line rather than emit the key twice. TOML forbids duplicate
    // keys, so emitting both would risk a parse error and a crash-loop instead
    // of an override — hence the explicit check rather than relying on
    // last-one-wins.
    if !additional_config_defines(extra_config, "MAX_ALLOWED_CLIENT_ACTIVE_STREAMS_PER_SESSION") {
        writeln!(
            body,
            "MAX_ALLOWED_CLIENT_ACTIVE_STREAMS_PER_SESSION = {MAX_STREAMS_PER_SESSION}"
        )
        .unwrap();
        body.push('\n');
    }

    // ------------------------------------------------------------------
    // 9) Logging
    // ------------------------------------------------------------------
    writeln!(body, "LOG_LEVEL = \"INFO\"").unwrap();
    body.push('\n');

    // ------------------------------------------------------------------
    // Verbatim escape hatch
    // ------------------------------------------------------------------
    if !extra_config.is_empty() {
        writeln!(body, "# --- operator additional_config (verbatim) ---").unwrap();
        body.push_str(extra_config);
        if !body.ends_with('\n') {
            body.push('\n');
        }
    }

    Ok(body)
}

/// Does the operator's verbatim `additional_config` already assign `key`?
///
/// Used to suppress our own emission of the same key. TOML forbids duplicate
/// keys, so "append the operator's block and let it win" is not a safe
/// override strategy — a duplicate risks a parse failure and a crash-loop
/// rather than an override.
///
/// Deliberately conservative: matches `KEY =` / `KEY=` at the start of a line
/// (leading whitespace allowed), skips comments, and is case-sensitive because
/// mdnsvpn's TOML keys are.
fn additional_config_defines(extra: &str, key: &str) -> bool {
    extra.lines().any(|line| {
        let line = line.trim_start();
        if line.starts_with('#') {
            return false;
        }
        let Some(rest) = line.strip_prefix(key) else {
            return false;
        };
        rest.trim_start().starts_with('=')
    })
}

/// Validate the inbound for "could mdnsvpn actually run with this?".
/// Cheap structural checks only — DNS reachability of `domains`,
/// NS-delegation correctness, etc. are deployment concerns.
pub fn validate(inbound: &MdnsvpnInbound) -> Result<()> {
    if inbound.port < 1 || inbound.port > 65535 {
        return Err(anyhow!(
            "MasterDnsVPN port must be 1..=65535, got {}",
            inbound.port
        ));
    }
    keys::validate_encryption_method(inbound.encryption_method)?;
    keys::validate_key(&inbound.encryption_key)?;

    // Domains array sanity. We don't try to validate the LDH grammar
    // here — operators sometimes use IDN-ish names or trailing-dot FQDNs;
    // mdnsvpn itself accepts whatever the JSON unwraps to.
    let domains = parse_json_string_array(&inbound.domains)
        .map_err(|e| anyhow!("MasterDnsVPN domains: {e}"))?;
    if domains.is_empty() {
        return Err(anyhow!(
            "MasterDnsVPN inbound has no `domains` — set at least one NS-delegated FQDN"
        ));
    }
    for d in &domains {
        let t = d.trim();
        if t.is_empty() || t.contains(' ') || t.contains('\t') {
            return Err(anyhow!(
                "MasterDnsVPN domain {d:?} contains whitespace or is empty"
            ));
        }
    }

    // Protocol type: only the two upstream-supported values are accepted.
    match inbound.protocol_type.as_str() {
        "SOCKS5" | "TCP" => {}
        other => {
            return Err(anyhow!(
                "MasterDnsVPN protocol_type must be \"SOCKS5\" or \"TCP\", got {other:?}"
            ))
        }
    }

    // TCP mode requires a forward target.
    if inbound.protocol_type == "TCP" {
        if inbound.forward_ip.trim().is_empty() {
            return Err(anyhow!(
                "MasterDnsVPN protocol_type=TCP requires a non-empty forward_ip"
            ));
        }
        if inbound.forward_port < 1 || inbound.forward_port > 65535 {
            return Err(anyhow!(
                "MasterDnsVPN protocol_type=TCP requires forward_port in 1..=65535 \
                 (got {})",
                inbound.forward_port
            ));
        }
    }
    // SOCKS5-with-external requires forward_ip + forward_port too.
    if inbound.protocol_type == "SOCKS5" && inbound.use_external_socks5 {
        if inbound.forward_ip.trim().is_empty() {
            return Err(anyhow!(
                "MasterDnsVPN use_external_socks5=true requires a non-empty forward_ip"
            ));
        }
        if inbound.forward_port < 1 || inbound.forward_port > 65535 {
            return Err(anyhow!(
                "MasterDnsVPN use_external_socks5=true requires forward_port \
                 in 1..=65535 (got {})",
                inbound.forward_port
            ));
        }
    }
    if inbound.socks5_auth {
        if inbound.socks5_user.is_empty() {
            return Err(anyhow!(
                "MasterDnsVPN socks5_auth=true requires a non-empty socks5_user"
            ));
        }
        if inbound.socks5_pass.is_empty() {
            return Err(anyhow!(
                "MasterDnsVPN socks5_auth=true requires a non-empty socks5_pass"
            ));
        }
    }
    Ok(())
}

/// Parse a JSON array of strings. Tolerates an empty string (treated as
/// `[]`) so an empty DB column doesn't make `validate()` panic on
/// invalid JSON.
fn parse_json_string_array(s: &str) -> std::result::Result<Vec<String>, String> {
    let trimmed = s.trim();
    if trimmed.is_empty() {
        return Ok(Vec::new());
    }
    let v: serde_json::Value = serde_json::from_str(trimmed)
        .map_err(|e| format!("not valid JSON: {e}"))?;
    let arr = v
        .as_array()
        .ok_or_else(|| "JSON value is not an array".to_string())?;
    let mut out = Vec::with_capacity(arr.len());
    for entry in arr {
        let s = entry
            .as_str()
            .ok_or_else(|| "array entry is not a string".to_string())?;
        out.push(s.to_string());
    }
    Ok(out)
}

fn bool_lit(b: bool) -> &'static str {
    if b {
        "true"
    } else {
        "false"
    }
}

/// Render a Rust string as a TOML basic string literal.
fn toml_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = std::fmt::Write::write_fmt(
                    &mut out,
                    format_args!("\\u{:04X}", c as u32),
                );
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn toml_string_array(items: &[String]) -> String {
    let mut out = String::from("[");
    for (i, s) in items.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&toml_string(s));
    }
    out.push(']');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn fixture() -> MdnsvpnInbound {
        MdnsvpnInbound {
            id: "mdnsvpn0".into(),
            domains: r#"["v.example.com"]"#.into(),
            port: 53,
            bind: "0.0.0.0".into(),
            encryption_method: 1,
            encryption_key: "0123456789abcdef0123456789abcdef".into(),
            protocol_type: "SOCKS5".into(),
            dns_upstream_servers: r#"["1.1.1.1:53","1.0.0.1:53"]"#.into(),
            forward_ip: String::new(),
            forward_port: 0,
            use_external_socks5: false,
            socks5_auth: false,
            socks5_user: String::new(),
            socks5_pass: String::new(),
            additional_config: String::new(),
            enabled: true,
            created_at: "now".into(),
            updated_at: "now".into(),
        }
    }

    #[test]
    fn happy_path_renders_required_sections() {
        let toml = generate(&fixture(), &PathBuf::from("/etc/coffeeblack/mdnsvpn"))
            .expect("generate succeeds");
        assert!(toml.contains(r#"DOMAIN = ["v.example.com"]"#));
        assert!(toml.contains("PROTOCOL_TYPE = \"SOCKS5\""));
        assert!(toml.contains("UDP_HOST = \"0.0.0.0\""));
        assert!(toml.contains("UDP_PORT = 53"));
        assert!(toml.contains("DATA_ENCRYPTION_METHOD = 1"));
        assert!(toml.contains("ENCRYPTION_KEY_FILE = \"/etc/coffeeblack/mdnsvpn/encrypt_key.txt\""));
        assert!(toml.contains("DNS_UPSTREAM_SERVERS = [\"1.1.1.1:53\", \"1.0.0.1:53\"]"));
        assert!(toml.contains("USE_EXTERNAL_SOCKS5 = false"));
        assert!(toml.contains("SOCKS5_AUTH = false"));
    }

    #[test]
    fn multi_domain_render() {
        let mut inbound = fixture();
        inbound.domains = r#"["a.example.com","b.example.com"]"#.into();
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains(r#"DOMAIN = ["a.example.com", "b.example.com"]"#));
    }

    #[test]
    fn additional_config_appended_verbatim() {
        let mut inbound = fixture();
        inbound.additional_config = "MAX_PACKET_SIZE = 65500\nUDP_READERS = 8\n".into();
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains("# --- operator additional_config (verbatim) ---"));
        assert!(toml.ends_with("UDP_READERS = 8\n"));
    }

    #[test]
    fn tcp_mode_requires_forward_target() {
        let mut inbound = fixture();
        inbound.protocol_type = "TCP".into();
        // Missing forward_ip — should fail
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
        inbound.forward_ip = "10.0.0.5".into();
        inbound.forward_port = 1080;
        // Now succeeds
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains("PROTOCOL_TYPE = \"TCP\""));
        assert!(toml.contains("FORWARD_IP = \"10.0.0.5\""));
        assert!(toml.contains("FORWARD_PORT = 1080"));
    }

    #[test]
    fn socks5_with_external_requires_forward_target() {
        let mut inbound = fixture();
        inbound.use_external_socks5 = true;
        // No forward target — should fail
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
        inbound.forward_ip = "192.168.1.100".into();
        inbound.forward_port = 1080;
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains("USE_EXTERNAL_SOCKS5 = true"));
        assert!(toml.contains("FORWARD_IP = \"192.168.1.100\""));
    }

    #[test]
    fn socks5_auth_renders_credentials() {
        let mut inbound = fixture();
        inbound.use_external_socks5 = true;
        inbound.forward_ip = "10.0.0.5".into();
        inbound.forward_port = 1080;
        inbound.socks5_auth = true;
        inbound.socks5_user = "admin".into();
        inbound.socks5_pass = "secret".into();
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains("SOCKS5_AUTH = true"));
        assert!(toml.contains("SOCKS5_USER = \"admin\""));
        assert!(toml.contains("SOCKS5_PASS = \"secret\""));
    }

    #[test]
    fn rejects_invalid_port() {
        let mut inbound = fixture();
        inbound.port = 0;
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
        inbound.port = 70000;
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
    }

    #[test]
    fn rejects_empty_domains() {
        let mut inbound = fixture();
        inbound.domains = "[]".into();
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
        inbound.domains = "".into();
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
    }

    #[test]
    fn rejects_invalid_encryption_method() {
        let mut inbound = fixture();
        inbound.encryption_method = 7;
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
    }

    #[test]
    fn rejects_invalid_protocol_type() {
        let mut inbound = fixture();
        inbound.protocol_type = "HTTP".into();
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
    }

    #[test]
    fn rejects_missing_encryption_key() {
        let mut inbound = fixture();
        inbound.encryption_key = String::new();
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
    }

    #[test]
    fn emits_per_session_stream_ceiling() {
        let toml = generate(&fixture(), &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains(&format!(
            "MAX_ALLOWED_CLIENT_ACTIVE_STREAMS_PER_SESSION = {MAX_STREAMS_PER_SESSION}"
        )));
    }

    #[test]
    fn operator_override_suppresses_our_stream_ceiling() {
        // TOML forbids duplicate keys, so emitting both would risk a parse
        // failure rather than an override.
        let mut inbound = fixture();
        inbound.additional_config =
            "MAX_ALLOWED_CLIENT_ACTIVE_STREAMS_PER_SESSION = 1024\n".into();
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert_eq!(
            toml.matches("MAX_ALLOWED_CLIENT_ACTIVE_STREAMS_PER_SESSION")
                .count(),
            1,
            "key emitted twice:\n{toml}"
        );
        assert!(toml.contains("MAX_ALLOWED_CLIENT_ACTIVE_STREAMS_PER_SESSION = 1024"));
    }

    #[test]
    fn commented_out_override_does_not_suppress_our_line() {
        let mut inbound = fixture();
        inbound.additional_config =
            "# MAX_ALLOWED_CLIENT_ACTIVE_STREAMS_PER_SESSION = 1024\n".into();
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains(&format!(
            "MAX_ALLOWED_CLIENT_ACTIVE_STREAMS_PER_SESSION = {MAX_STREAMS_PER_SESSION}"
        )));
    }

    #[test]
    fn non_aead_method_emits_a_warning_block() {
        let mut inbound = fixture();
        inbound.encryption_method = 1; // XOR
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains("NOT authenticated encryption"), "{toml}");
        assert!(toml.contains("XOR"), "{toml}");
        // Still a valid, non-fatal config — the tunnel keys are all present.
        assert!(toml.contains("DATA_ENCRYPTION_METHOD = 1"));
    }

    #[test]
    fn aead_method_emits_no_warning_block() {
        let mut inbound = fixture();
        inbound.encryption_method = keys::RECOMMENDED_ENCRYPTION_METHOD;
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(!toml.contains("NOT authenticated encryption"), "{toml}");
        assert!(toml.contains(&format!(
            "DATA_ENCRYPTION_METHOD = {}",
            keys::RECOMMENDED_ENCRYPTION_METHOD
        )));
    }

    #[test]
    fn additional_config_defines_matches_only_real_assignments() {
        assert!(additional_config_defines("FOO = 1", "FOO"));
        assert!(additional_config_defines("  FOO=1", "FOO"));
        assert!(additional_config_defines("A = 1\nFOO = 2\n", "FOO"));
        // Not assignments / not this key.
        assert!(!additional_config_defines("# FOO = 1", "FOO"));
        assert!(!additional_config_defines("FOOBAR = 1", "FOO"));
        assert!(!additional_config_defines("BAR = 1", "FOO"));
        assert!(!additional_config_defines("", "FOO"));
        // Case-sensitive, like mdnsvpn's TOML keys.
        assert!(!additional_config_defines("foo = 1", "FOO"));
    }

    #[test]
    fn toml_escapes_quotes_in_strings() {
        let mut inbound = fixture();
        inbound.forward_ip = r#"ev"il\path"#.into();
        inbound.protocol_type = "TCP".into();
        inbound.forward_port = 1080;
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains(r#"FORWARD_IP = "ev\"il\\path""#));
    }
}
