//! Encryption-key generator + validator for MasterDnsVPN.
//!
//! The upstream `-genkey` flag produces a 16-byte random key encoded as
//! 32 lowercase-hex characters. We match that format exactly so a key
//! generated by awg-easy-rs is drop-in compatible with operators who
//! mix-and-match against vanilla MasterDnsVPN setups (e.g. for testing).
//!
//! The key is a single shared secret: every client uses the same value.
//! That's a property of MasterDnsVPN itself — its protocol has no
//! per-user secret slot. Per-user records in `mdnsvpn_clients_table`
//! are just bookkeeping for the share-link UX.

use anyhow::{anyhow, Result};

/// Length (in hex characters) of a freshly-generated key. 32 chars = 16
/// raw bytes — what upstream `mdnsvpn -genkey` produces. The encryption
/// engine is tolerant of longer keys (it KDFs internally for AES-256),
/// but matching upstream's default keeps share-formats interoperable.
pub const DEFAULT_KEY_HEX_LEN: usize = 32;

/// Minimum length operators are allowed to set. Below 16 hex chars
/// (8 bytes) every encryption method is meaningfully weakened — the
/// upstream README explicitly warns against short keys.
pub const MIN_KEY_HEX_LEN: usize = 16;

/// Generate a fresh random 16-byte key, hex-encoded. Uses `OsRng`, the
/// OS CSPRNG (same source the rest of awg-easy-rs uses for session
/// passwords + AmneziaWG private keys).
pub fn generate_key() -> String {
    let mut bytes = [0u8; DEFAULT_KEY_HEX_LEN / 2];
    crate::rng::fill(&mut bytes);
    hex::encode(bytes)
}

/// Validate a key-as-stored: must be lowercase or uppercase hex, even
/// length, and at least `MIN_KEY_HEX_LEN` characters. The mdnsvpn
/// binary itself accepts arbitrary ASCII for `ENCRYPTION_KEY`, but
/// constraining to hex keeps the share-format unambiguous (no
/// escaping issues in TOML / URLs / QR codes).
pub fn validate_key(key: &str) -> Result<()> {
    let k = key.trim();
    if k.is_empty() {
        return Err(anyhow!("encryption key must not be empty"));
    }
    if k.len() < MIN_KEY_HEX_LEN {
        return Err(anyhow!(
            "encryption key must be at least {MIN_KEY_HEX_LEN} hex chars (got {} chars)",
            k.len()
        ));
    }
    if !k.len().is_multiple_of(2) {
        return Err(anyhow!(
            "encryption key must have an even number of hex characters (got {})",
            k.len()
        ));
    }
    if !k.chars().all(|c| c.is_ascii_hexdigit()) {
        return Err(anyhow!(
            "encryption key contains non-hex characters — only [0-9a-fA-F] are allowed"
        ));
    }
    Ok(())
}

/// Validate the integer encryption-method selector against the
/// upstream-defined set (0..=5). See `DATA_ENCRYPTION_METHOD` in the
/// upstream README for the meaning of each value.
pub fn validate_encryption_method(method: i64) -> Result<()> {
    match method {
        0..=5 => Ok(()),
        _ => Err(anyhow!(
            "DATA_ENCRYPTION_METHOD must be 0..=5 (got {method}). \
             0=None 1=XOR 2=ChaCha20 3=AES-128-GCM 4=AES-192-GCM 5=AES-256-GCM"
        )),
    }
}

/// Method we default new deployments to: AES-256-GCM.
///
/// Safe to select for *any* key we accept — upstream derives the AES key
/// with `sha256(rawKey)` for methods 2 and 5 (`internal/security/codec.go`,
/// `deriveKey`), so moving an existing key from method 1 to method 5 needs
/// no re-keying. It does need every already-distributed client config to be
/// re-issued, because the method itself is baked into each client config.
pub const RECOMMENDED_ENCRYPTION_METHOD: i64 = 5;

/// Does this method authenticate the ciphertext?
///
/// Only the AES-GCM methods (3, 4, 5) are AEAD. Method 0 is plaintext,
/// method 1 is XOR against a repeating key (neither confidential nor
/// authenticated), and method 2 is bare ChaCha20 without Poly1305 — so an
/// active on-path attacker can tamper with tunnel payloads undetected on
/// 0/1/2. Upstream's method numbering hides this, hence the helper.
pub fn is_aead(method: i64) -> bool {
    matches!(method, 3..=5)
}

/// Human-readable name for a `DATA_ENCRYPTION_METHOD` value.
pub fn method_name(method: i64) -> &'static str {
    match method {
        0 => "None",
        1 => "XOR",
        2 => "ChaCha20",
        3 => "AES-128-GCM",
        4 => "AES-192-GCM",
        5 => "AES-256-GCM",
        _ => "unknown",
    }
}

/// Non-reversible identifier for a key: the first 8 hex chars of
/// SHA-256(key).
///
/// Operators need *some* way to confirm a server and a client loaded the
/// same shared secret. A fingerprint gives them that without the secret
/// itself ever reaching a log stream, a support ticket, or a screenshot.
pub fn key_fingerprint(key: &str) -> String {
    crate::auth::sha256(key.trim()).chars().take(8).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_key_is_lowercase_hex_of_default_length() {
        for _ in 0..16 {
            let k = generate_key();
            assert_eq!(k.len(), DEFAULT_KEY_HEX_LEN);
            assert!(k.chars().all(|c| c.is_ascii_hexdigit()));
            assert!(k.chars().all(|c| !c.is_ascii_uppercase()));
        }
    }

    #[test]
    fn generated_keys_are_unique() {
        // Trivially-flakey collision check — but 16 bytes from OsRng has
        // a 2^-128 collision probability so this never spuriously fails.
        let a = generate_key();
        let b = generate_key();
        assert_ne!(a, b);
    }

    #[test]
    fn validate_accepts_hex_at_min_length() {
        validate_key("0123456789abcdef").unwrap();
    }

    #[test]
    fn validate_rejects_empty() {
        assert!(validate_key("").is_err());
        assert!(validate_key("   ").is_err());
    }

    #[test]
    fn validate_rejects_too_short() {
        assert!(validate_key("abcdef").is_err());
    }

    #[test]
    fn validate_rejects_odd_length() {
        assert!(validate_key("0123456789abcde").is_err());
    }

    #[test]
    fn validate_rejects_non_hex() {
        assert!(validate_key("zzzz5678zzzz5678").is_err());
    }

    #[test]
    fn validate_accepts_uppercase_hex() {
        // Hex itself is case-tolerant; we accept what the user types.
        validate_key("0123456789ABCDEF").unwrap();
    }

    #[test]
    fn validate_encryption_method_range() {
        for m in 0..=5 {
            validate_encryption_method(m).unwrap();
        }
        assert!(validate_encryption_method(-1).is_err());
        assert!(validate_encryption_method(6).is_err());
        assert!(validate_encryption_method(99).is_err());
    }

    #[test]
    fn only_aes_gcm_methods_are_aead() {
        for m in 0..=2 {
            assert!(!is_aead(m), "method {m} must not be treated as AEAD");
        }
        for m in 3..=5 {
            assert!(is_aead(m), "method {m} must be treated as AEAD");
        }
        assert!(is_aead(RECOMMENDED_ENCRYPTION_METHOD));
    }

    #[test]
    fn recommended_method_is_valid_and_named() {
        validate_encryption_method(RECOMMENDED_ENCRYPTION_METHOD).unwrap();
        assert_eq!(method_name(RECOMMENDED_ENCRYPTION_METHOD), "AES-256-GCM");
        assert_eq!(method_name(1), "XOR");
        assert_eq!(method_name(42), "unknown");
    }

    #[test]
    fn fingerprint_is_short_hex_and_hides_the_key() {
        let key = "deadbeefcafebabe1234567890abcdef";
        let fp = key_fingerprint(key);
        assert_eq!(fp.len(), 8);
        assert!(fp.chars().all(|c| c.is_ascii_hexdigit()));
        // The point of the whole exercise: the key must not be recoverable
        // from, or textually present in, the fingerprint.
        assert!(!key.contains(&fp));
        assert!(!fp.contains(key));
    }

    #[test]
    fn fingerprint_is_stable_and_ignores_surrounding_whitespace() {
        let a = key_fingerprint("0123456789abcdef");
        let b = key_fingerprint("  0123456789abcdef\n");
        assert_eq!(a, b);
        assert_ne!(a, key_fingerprint("0123456789abcdee"));
    }
}
