//! Privilege separation: a root helper behind a fixed operation allowlist.
//!
//! Ported from the model in [islandr-proxy](https://github.com/chriscohnen/islandr)
//! (ADR-0012), adapted to this project's single-binary shape — the helper is a
//! subcommand of the same executable (`awg-easy-rs --privileged-helper`)
//! rather than a second artefact to build, ship, and version.
//!
//! ## The problem
//!
//! The web UI and the interface manager are the same process, and that process
//! runs as root because `awg-quick`, `awg` and `nft` need `CAP_NET_ADMIN`. So
//! any remote-code-execution bug in the HTTP layer — a parser, a dependency, a
//! handler — is instantly full control of the host. The privileged work is a
//! handful of operations; the attack surface carrying that privilege is an
//! entire web application.
//!
//! ## The split
//!
//! The helper runs as root on a Unix socket and speaks one line-delimited JSON
//! request per connection. It accepts a **fixed allowlist of operations**,
//! each executed as an argument vector — never a shell string, never a command
//! name taken from the request. The interface name and every filesystem path
//! are fixed when the helper starts and are not accepted from the wire, so a
//! caller cannot redirect an operation at another interface or another file.
//!
//! The main process then needs no capabilities at all for these operations.
//!
//! ## What this does and does not buy
//!
//! Be precise about this, because the pattern is easy to over-sell:
//!
//! - It **removes** arbitrary code execution as root, arbitrary file read and
//!   write, module loading, and persistence — the things an attacker actually
//!   wants from an RCE.
//! - It **does not** remove control of the VPN. A compromised main process can
//!   still ask for a ruleset to be applied and an interface to be
//!   reconfigured, because that is the service's entire purpose. The ruleset
//!   text is generated by the unprivileged side; the helper validates that it
//!   parses (`nft -c`) but cannot judge whether the operator wanted it.
//!
//! So it converts "root on the box" into "control of the tunnel". That is a
//! large reduction, and it is not containment.
//!
//! Operations that genuinely still need privilege and are **out of scope**
//! here: loading the `amneziawg` kernel module (done once at unit start via
//! `ExecStartPre=`), and binding the low ports the optional bundled transports
//! use (Xray on 443, MasterDnsVPN on 53) — grant those with
//! `CAP_NET_BIND_SERVICE` or leave those transports disabled.

use std::io::{BufRead, BufReader, Read, Write};
use std::os::unix::fs::PermissionsExt;
use std::os::unix::net::{UnixListener, UnixStream};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use anyhow::{anyhow, Context, Result};
use serde::{Deserialize, Serialize};

/// Default socket path. Overridden with `WG_EASY_HELPER_SOCKET`.
pub const DEFAULT_SOCKET: &str = "/run/awg-easy-rs/helper.sock";

/// Largest request accepted, in bytes. Generated nftables rulesets for a large
/// roster are a few tens of kilobytes; a megabyte is far above any legitimate
/// value and bounds what a compromised caller can make the helper buffer.
const MAX_REQUEST_BYTES: u64 = 1024 * 1024;

// ---------------------------------------------------------------------------
// Wire format
// ---------------------------------------------------------------------------

/// One request. `op` selects from the allowlist; nothing here names a binary,
/// an interface, or a path.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum Request {
    /// `awg-quick up <iface>`
    WgUp,
    /// `awg-quick down <iface>`
    WgDown,
    /// Write the interface config, then `awg syncconf` it into the running
    /// interface without a restart.
    WgSync { config: String },
    /// `awg show <iface> dump`
    WgShow,
    /// Validate and apply an nftables ruleset (`nft -c -f -`, then `nft -f -`).
    NftApply { ruleset: String },
    /// `nft <args>` restricted to read-only listing of this project's table.
    NftList,
    /// Liveness probe.
    Ping,
}

/// One response, always a single JSON line.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Response {
    pub ok: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl Response {
    fn ok(output: impl Into<String>) -> Self {
        Response { ok: true, output: Some(output.into()), error: None }
    }
    fn err(error: impl Into<String>) -> Self {
        Response { ok: false, output: None, error: Some(error.into()) }
    }
}

// ---------------------------------------------------------------------------
// Server
// ---------------------------------------------------------------------------

/// Everything the helper will touch, fixed at startup. None of it is
/// influenced by a request — that is the property the whole design rests on.
pub struct HelperConfig {
    pub socket_path: PathBuf,
    pub interface: String,
    pub conf_dir: PathBuf,
    /// gid allowed to connect. The socket is chmod 0660 and chowned to this
    /// group so exactly one unprivileged account can reach it, rather than
    /// every local user.
    pub allow_gid: Option<u32>,
}

impl HelperConfig {
    /// The config file this helper is willing to write. Derived from the fixed
    /// interface name, so `WgSync` cannot be pointed anywhere else.
    fn conf_path(&self) -> PathBuf {
        self.conf_dir.join(format!("{}.conf", self.interface))
    }
}

/// Run the helper until the process is killed. Blocking; intended to be the
/// whole of `main` for the `--privileged-helper` subcommand.
pub fn serve(cfg: HelperConfig) -> Result<()> {
    if let Some(parent) = cfg.socket_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("create socket dir {}", parent.display()))?;
    }
    // A stale socket from an unclean shutdown makes bind() fail with EADDRINUSE
    // even though nothing is listening.
    if cfg.socket_path.exists() {
        std::fs::remove_file(&cfg.socket_path).ok();
    }

    // Narrow the umask across bind(). `UnixListener::bind` creates the socket
    // with the process umask applied, and only then can it be chmod'ed — so a
    // default 0022 umask leaves a window where the socket exists mode 0755 and
    // any local user can connect and drive the tunnel. Setting the umask first
    // closes the window instead of racing it. (Same bug class the DB snapshot
    // path documents: chmod-after-create is not good enough for a secret.)
    let prev_umask = unsafe { libc::umask(0o177) };
    let bound = UnixListener::bind(&cfg.socket_path);
    unsafe { libc::umask(prev_umask) };
    let listener = bound.with_context(|| format!("bind {}", cfg.socket_path.display()))?;

    // Default to 0600 (root only) and widen to 0660 only when a group was
    // named. Getting this wrong in the permissive direction would hand every
    // local account the ability to reconfigure the tunnel, so the tight mode
    // is the one that needs no argument.
    let mode = if cfg.allow_gid.is_some() { 0o660 } else { 0o600 };
    std::fs::set_permissions(&cfg.socket_path, std::fs::Permissions::from_mode(mode))
        .context("chmod helper socket")?;
    if let Some(gid) = cfg.allow_gid {
        chown_gid(&cfg.socket_path, gid)
            .with_context(|| format!("chown helper socket to gid {gid}"))?;
    }

    tracing::info!(
        "privileged helper listening on {} (interface {}, mode {:o})",
        cfg.socket_path.display(),
        cfg.interface,
        mode
    );

    for stream in listener.incoming() {
        match stream {
            Ok(s) => {
                if let Err(e) = handle_connection(&cfg, s) {
                    // One bad connection must never take the helper down: it
                    // is the only path the main process has to the interface.
                    tracing::warn!("helper connection failed: {e:#}");
                }
            }
            Err(e) => tracing::warn!("helper accept failed: {e}"),
        }
    }
    Ok(())
}

fn handle_connection(cfg: &HelperConfig, stream: UnixStream) -> Result<()> {
    let mut reader = BufReader::new(stream.try_clone()?);
    let mut line = String::new();
    // Bounded read: an unterminated line from a compromised caller must not
    // grow until the helper is OOM-killed.
    reader
        .by_ref()
        .take(MAX_REQUEST_BYTES)
        .read_line(&mut line)?;

    let response = match serde_json::from_str::<Request>(line.trim()) {
        Ok(req) => dispatch(cfg, req),
        // Deliberately does not echo the input back: the error goes to a log
        // the caller may be able to read.
        Err(e) => Response::err(format!("malformed request: {e}")),
    };

    let mut out = stream;
    let mut body = serde_json::to_string(&response)?;
    body.push('\n');
    out.write_all(body.as_bytes())?;
    out.flush()?;
    Ok(())
}

fn dispatch(cfg: &HelperConfig, req: Request) -> Response {
    let result = match req {
        Request::Ping => Ok("pong".to_string()),
        Request::WgUp => run(&["awg-quick", "up", &cfg.interface]).map(|_| String::new()),
        Request::WgDown => run(&["awg-quick", "down", &cfg.interface]).map(|_| String::new()),
        Request::WgShow => run(&["awg", "show", &cfg.interface, "dump"]),
        Request::WgSync { config } => wg_sync(cfg, &config).map(|_| String::new()),
        Request::NftApply { ruleset } => nft_apply(&ruleset).map(|_| String::new()),
        Request::NftList => run(&["nft", "list", "table", "inet", "awg-easy-rs"]),
    };
    match result {
        Ok(output) => Response::ok(output),
        Err(e) => Response::err(format!("{e:#}")),
    }
}

/// Write the interface config and sync it into the running interface.
///
/// The path is derived from the helper's fixed interface name, never from the
/// request, so this cannot be turned into an arbitrary-file-write primitive —
/// which is the single most valuable thing an attacker could extract from a
/// root helper.
fn wg_sync(cfg: &HelperConfig, config: &str) -> Result<()> {
    let path = cfg.conf_path();
    std::fs::create_dir_all(&cfg.conf_dir).ok();
    // Create with 0600 rather than writing and chmod'ing afterwards: this file
    // carries the server private key, and `fs::write` + `set_permissions`
    // leaves it world-readable for the duration of the write. `.mode()` is
    // applied by open(2) itself, so there is no window at all.
    {
        use std::os::unix::fs::OpenOptionsExt;
        let mut f = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(&path)
            .with_context(|| format!("open {}", path.display()))?;
        f.write_all(config.as_bytes())
            .with_context(|| format!("write {}", path.display()))?;
    }
    // An existing file keeps its old mode through O_CREAT, so still enforce it.
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))
        .with_context(|| format!("chmod {}", path.display()))?;

    // Interface not up yet: writing the config is the whole job, and the next
    // `WgUp` will read it. Not an error.
    if run(&["awg", "show", &cfg.interface]).is_err() {
        return Ok(());
    }
    let stripped = run(&["awg-quick", "strip", &cfg.interface])?;
    run_with_stdin(&["awg", "syncconf", &cfg.interface, "/dev/stdin"], &stripped).map(|_| ())
}

/// Validate then apply an nftables ruleset.
///
/// The dry run is not cosmetic: `nft -f` applies statements up to the point it
/// fails, so an invalid ruleset can leave the firewall half-built — open in
/// ways neither the old nor the new ruleset describes. `-c` parses the whole
/// thing first, making application all-or-nothing in practice.
fn nft_apply(ruleset: &str) -> Result<()> {
    run_with_stdin(&["nft", "-c", "-f", "/dev/stdin"], ruleset)
        .context("nftables ruleset failed validation; not applied")?;
    run_with_stdin(&["nft", "-f", "/dev/stdin"], ruleset).map(|_| ())
}

/// Execute an argument vector. No shell, and `argv[0]` always comes from a
/// literal in this file — never from a request.
fn run(argv: &[&str]) -> Result<String> {
    let (prog, args) = argv.split_first().ok_or_else(|| anyhow!("empty argv"))?;
    let out = Command::new(prog)
        .args(args)
        .output()
        .with_context(|| format!("spawn {prog}"))?;
    if !out.status.success() {
        return Err(anyhow!(
            "{prog} failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

fn run_with_stdin(argv: &[&str], input: &str) -> Result<String> {
    let (prog, args) = argv.split_first().ok_or_else(|| anyhow!("empty argv"))?;
    let mut child = Command::new(prog)
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .with_context(|| format!("spawn {prog}"))?;
    if let Some(mut sin) = child.stdin.take() {
        sin.write_all(input.as_bytes())?;
    }
    let out = child.wait_with_output()?;
    if !out.status.success() {
        return Err(anyhow!(
            "{prog} failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

/// `chown :gid` on the socket. `None` for uid leaves the owner (root) alone.
fn chown_gid(path: &Path, gid: u32) -> Result<()> {
    std::os::unix::fs::chown(path, None, Some(gid))?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Client
// ---------------------------------------------------------------------------

/// Path of the helper socket, if this process is configured to use one.
///
/// `None` means no helper: callers fall back to executing the commands
/// directly, which is the pre-existing single-process behaviour and remains
/// the default so an upgrade changes nothing until the operator opts in.
pub fn socket_path() -> Option<PathBuf> {
    match std::env::var("WG_EASY_HELPER_SOCKET") {
        Ok(p) if !p.is_empty() => Some(PathBuf::from(p)),
        _ => None,
    }
}

/// True when this process should route privileged work through the helper.
pub fn is_enabled() -> bool {
    socket_path().is_some()
}

/// Send one request and read one response.
pub fn call(req: &Request) -> Result<String> {
    let path = socket_path().ok_or_else(|| anyhow!("helper socket not configured"))?;
    let stream = UnixStream::connect(&path)
        .with_context(|| format!("connect helper socket {}", path.display()))?;

    let mut body = serde_json::to_string(req)?;
    body.push('\n');
    (&stream).write_all(body.as_bytes())?;
    (&stream).flush()?;

    let mut reader = BufReader::new(&stream);
    let mut line = String::new();
    reader
        .by_ref()
        .take(MAX_REQUEST_BYTES)
        .read_line(&mut line)?;

    let resp: Response =
        serde_json::from_str(line.trim()).context("helper returned a malformed response")?;
    if resp.ok {
        Ok(resp.output.unwrap_or_default())
    } else {
        Err(anyhow!(
            "helper refused: {}",
            resp.error.unwrap_or_else(|| "unknown error".into())
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn requests_round_trip_as_tagged_json() {
        let r = Request::WgSync { config: "[Interface]\n".into() };
        let s = serde_json::to_string(&r).unwrap();
        assert!(s.contains("\"op\":\"wg_sync\""));
        assert!(matches!(
            serde_json::from_str::<Request>(&s).unwrap(),
            Request::WgSync { .. }
        ));
    }

    #[test]
    fn unknown_ops_are_rejected() {
        // The allowlist is the enum: anything not named in it fails to parse,
        // so there is no path from the wire to an arbitrary command.
        assert!(serde_json::from_str::<Request>(r#"{"op":"exec","cmd":"sh"}"#).is_err());
        assert!(serde_json::from_str::<Request>(r#"{"op":"wg_up","iface":"other"}"#).is_ok());
    }

    #[test]
    fn interface_name_in_a_request_is_ignored() {
        // A caller may send extra fields; none of them can redirect the
        // operation, because dispatch reads the interface from HelperConfig.
        let req: Request =
            serde_json::from_str(r#"{"op":"wg_show","interface":"eth0"}"#).unwrap();
        assert!(matches!(req, Request::WgShow));
    }

    #[test]
    fn conf_path_is_derived_from_the_fixed_interface() {
        let cfg = HelperConfig {
            socket_path: "/run/x.sock".into(),
            interface: "awg0".into(),
            conf_dir: "/etc/wireguard".into(),
            allow_gid: None,
        };
        assert_eq!(cfg.conf_path(), Path::new("/etc/wireguard/awg0.conf"));
    }

    #[test]
    fn responses_round_trip() {
        let r: Response = serde_json::from_str(r#"{"ok":true,"output":"x"}"#).unwrap();
        assert!(r.ok);
        assert_eq!(r.output.as_deref(), Some("x"));
        let e: Response = serde_json::from_str(r#"{"ok":false,"error":"nope"}"#).unwrap();
        assert!(!e.ok);
    }
}
