//! Generate `dnscrypt-proxy.toml` from `db::DnsBundle` state.
//!
//! The output is a complete config — dnscrypt-proxy doesn't merge
//! multiple files at runtime. We re-render the entire file every time
//! the supervisor reconciles, then SIGHUP the child so it re-reads.
//!
//! ## Why we hardcode certain things
//!
//! A full dnscrypt-proxy config has dozens of knobs. We only surface the
//! ones an operator needs to make security-relevant decisions, and
//! pin the rest to "sensible secure defaults" that match what Wiregate
//! ships:
//!
//! - `cache = true` with conservative TTLs (10 min min, 24 h max). Cuts
//!   query volume to upstream servers without leaking DNSSEC signature
//!   freshness windows beyond a day.
//! - `force_tcp = true`. dnscrypt-proxy can downgrade to UDP for plain
//!   DNS, but we don't want that — TCP-only across the wire keeps
//!   middleboxes from MITM-ing DoH negotiation on UDP/443.
//! - `dnscrypt_ephemeral_keys = true`. Forward secrecy on the DNSCrypt
//!   session (per query, costs ~400 µs of client CPU).
//! - `block_ipv6 = false`. Don't second-guess the operator's network
//!   stack — peers may legitimately need v6 PTR / AAAA records.
//! - `ignore_system_dns = true`. Never fall back to /etc/resolv.conf if
//!   bootstrap resolution fails — that's a recipe for silent leakage.
//!
//! `additional_config` is appended verbatim AFTER all our keys, which
//! means a TOML key the operator declares there overrides ours.

use anyhow::{anyhow, Result};
use serde_json::Value;

use crate::db;

/// Render the full TOML body. Caller writes this to disk and points
/// dnscrypt-proxy at it via `-config <path>`.
pub fn generate(bundle: &db::DnsBundle) -> Result<String> {
    if bundle.listen_port < 1 || bundle.listen_port > 65535 {
        return Err(anyhow!(
            "DNS bundle listen_port {} is out of range",
            bundle.listen_port
        ));
    }
    let resolvers = parse_resolvers(&bundle.upstream_resolvers)?;

    let mut toml = String::new();
    toml.push_str("# Generated by awg-easy-rs — do NOT hand-edit; changes are\n");
    toml.push_str("# overwritten on every supervisor reconcile.\n\n");

    // Listen address: bind to all interfaces. The DNS lockdown DNAT
    // rules redirect peer :53/:853 to <wg server>:<listen_port>, so
    // dnscrypt-proxy has to be reachable on the WG-facing IP. Binding
    // to 0.0.0.0 covers that without forcing the operator to set the
    // exact IP in dnscrypt config too.
    toml.push_str(&format!(
        "listen_addresses = ['0.0.0.0:{port}', '[::]:{port}']\n",
        port = bundle.listen_port
    ));
    toml.push_str("max_clients = 250\n");
    toml.push_str("ipv4_servers = true\n");
    toml.push_str("ipv6_servers = true\n");
    toml.push_str("dnscrypt_servers = true\n");
    toml.push_str("doh_servers = true\n");
    toml.push_str("odoh_servers = false\n");
    toml.push_str(&format!(
        "require_dnssec = {}\n",
        toml_bool(bundle.require_dnssec)
    ));
    toml.push_str(&format!(
        "require_nolog = {}\n",
        toml_bool(bundle.require_nolog)
    ));
    toml.push_str(&format!(
        "require_nofilter = {}\n",
        toml_bool(bundle.require_nofilter)
    ));
    toml.push_str("force_tcp = true\n");
    toml.push_str("timeout = 5000\n");
    toml.push_str("keepalive = 30\n");
    toml.push_str("cert_refresh_delay = 240\n");
    toml.push_str("dnscrypt_ephemeral_keys = true\n");
    toml.push_str("tls_disable_session_tickets = true\n");
    toml.push_str("ignore_system_dns = true\n");
    toml.push_str("netprobe_timeout = 60\n");
    toml.push_str("netprobe_address = '9.9.9.9:53'\n");
    toml.push_str("block_ipv6 = false\n");
    toml.push_str("block_unqualified = true\n");
    toml.push_str("block_undelegated = true\n");
    toml.push_str("reject_ttl = 10\n");

    // Cache.
    toml.push_str("cache = true\n");
    toml.push_str("cache_size = 4096\n");
    toml.push_str("cache_min_ttl = 600\n");
    toml.push_str("cache_max_ttl = 86400\n");
    toml.push_str("cache_neg_min_ttl = 60\n");
    toml.push_str("cache_neg_max_ttl = 600\n");

    // Bootstrap — used only to resolve the DoH/DNSCrypt server hostnames
    // themselves on first run. Quad9-by-IP is well-known and refuses
    // ANY-amplification queries.
    toml.push_str("bootstrap_resolvers = ['9.9.9.9:53', '149.112.112.112:53']\n");

    // Upstream resolver pinning.
    if resolvers.is_empty() {
        // Auto: dnscrypt-proxy picks from public-resolvers.md sources.
        toml.push_str("# server_names commented out — dnscrypt-proxy auto-selects\n");
    } else {
        // Explicit list. dnscrypt-proxy only uses these and ignores
        // anything else from the sources file.
        toml.push_str("server_names = [");
        for (i, name) in resolvers.iter().enumerate() {
            if i > 0 {
                toml.push_str(", ");
            }
            toml.push('\'');
            toml.push_str(&escape_toml_string(name));
            toml.push('\'');
        }
        toml.push_str("]\n");
    }

    // Tor SOCKS routing — opt-in. When tor_enabled is true, every
    // upstream DoH/DNSCrypt request gets tunnelled through the local
    // tor SOCKS port. This is the line Wiregate's entrypoint.sh
    // un-comments when WGD_TOR_PROXY=true.
    if bundle.tor_enabled {
        toml.push_str(&format!(
            "proxy = 'socks5://127.0.0.1:{port}'\n",
            port = bundle.tor_socks_port
        ));
    }

    // Operator additional_config goes here, BEFORE the first table header.
    // TOML scopes bare `key = value` lines to the most recent [table], so
    // appending this after `[sources.'public-resolvers']` (as it used to be)
    // silently reparented every operator key into that table — where
    // dnscrypt-proxy ignores it. An operator hardening the resolver would see
    // their setting accepted and have no effect, which is worse than a
    // rejection. At top level the documented "operator keys override ours"
    // behaviour actually holds, since dnscrypt-proxy takes the last value.
    if !bundle.additional_config.trim().is_empty() {
        toml.push_str("\n# --- operator-supplied additional_config ---\n");
        toml.push_str(bundle.additional_config.trim_end());
        toml.push('\n');
    }

    // Sources — the upstream public-resolvers list. Pinned to the
    // canonical dnscrypt-resolvers project mirror with the maintainer's
    // minisign key. Without this dnscrypt-proxy can't auto-discover
    // resolvers, but with it our `server_names` lookup works.
    toml.push_str("\n[sources]\n");
    toml.push_str("\n[sources.'public-resolvers']\n");
    toml.push_str(
        "urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', \
         'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']\n",
    );
    toml.push_str("minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'\n");
    toml.push_str("cache_file = 'public-resolvers.md'\n");
    toml.push_str("refresh_delay = 73\n");
    toml.push_str("prefix = ''\n");

    Ok(toml)
}

/// Decode the `upstream_resolvers` JSON-array field. Empty / `[]` /
/// `null` all map to "auto-select"; anything else must be a JSON array
/// of resolver-name strings.
fn parse_resolvers(json: &str) -> Result<Vec<String>> {
    let trimmed = json.trim();
    if trimmed.is_empty() || trimmed == "null" {
        return Ok(Vec::new());
    }
    let v: Value = serde_json::from_str(trimmed)
        .map_err(|e| anyhow!("upstream_resolvers is not valid JSON: {e}"))?;
    let arr = v
        .as_array()
        .ok_or_else(|| anyhow!("upstream_resolvers must be a JSON array of strings"))?;
    let mut out = Vec::with_capacity(arr.len());
    for entry in arr {
        let s = entry
            .as_str()
            .ok_or_else(|| anyhow!("upstream_resolvers entries must be strings"))?
            .trim();
        if s.is_empty() {
            continue;
        }
        // dnscrypt-proxy resolver names are alnum + dash + dot; reject
        // anything weirder so a malicious operator can't smuggle TOML
        // syntax (e.g. close-quote-then-key) through the field.
        if !s
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '.' | '_'))
        {
            return Err(anyhow!(
                "upstream_resolvers entry {s:?} contains characters outside [A-Za-z0-9._-]"
            ));
        }
        out.push(s.to_string());
    }
    Ok(out)
}

fn toml_bool(b: bool) -> &'static str {
    if b { "true" } else { "false" }
}

/// Escape a string for inclusion inside a TOML single-quoted literal.
/// Single-quoted literals don't process escapes, so we just need to
/// reject the literal `'` character (which terminates the string).
/// Combined with `parse_resolvers`'s charset filter, this is defense in
/// depth.
fn escape_toml_string(s: &str) -> String {
    s.chars().filter(|c| *c != '\'').collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(enabled: bool) -> db::DnsBundle {
        db::DnsBundle {
            id: "dns0".into(),
            enabled,
            listen_port: 5353,
            upstream_resolvers: "[]".into(),
            require_dnssec: true,
            require_nolog: true,
            require_nofilter: false,
            tor_enabled: false,
            tor_socks_port: 9053,
            tor_exit_nodes: String::new(),
            tor_dns_exit_nodes: String::new(),
            tor_use_bridges: false,
            tor_plugin: String::new(),
            additional_config: String::new(),
            created_at: "now".into(),
            updated_at: "now".into(),
        }
    }

    #[test]
    fn baseline_config_has_listen_and_security_keys() {
        let body = generate(&fixture(true)).unwrap();
        // Listen on the configured port, both v4 and v6.
        assert!(body.contains("listen_addresses = ['0.0.0.0:5353', '[::]:5353']"));
        // Security defaults should be locked in.
        assert!(body.contains("require_dnssec = true"));
        assert!(body.contains("require_nolog = true"));
        assert!(body.contains("force_tcp = true"));
        assert!(body.contains("dnscrypt_ephemeral_keys = true"));
        assert!(body.contains("ignore_system_dns = true"));
        assert!(body.contains("tls_disable_session_tickets = true"));
        // No tor proxy line when tor_enabled is false.
        assert!(!body.contains("socks5://"));
        assert!(!body.contains("proxy ="));
    }

    #[test]
    fn empty_resolvers_means_auto_select() {
        let body = generate(&fixture(true)).unwrap();
        // server_names should be commented out, not absent — operators
        // need to see what the auto-select state means.
        assert!(body.contains("# server_names commented out"));
        assert!(!body.contains("server_names = ["));
    }

    #[test]
    fn explicit_resolvers_emitted_as_array() {
        let mut b = fixture(true);
        b.upstream_resolvers = r#"["cloudflare", "quad9-doh-ip4-port443-filter-pri"]"#.into();
        let body = generate(&b).unwrap();
        assert!(body.contains(
            "server_names = ['cloudflare', 'quad9-doh-ip4-port443-filter-pri']"
        ));
    }

    #[test]
    fn resolver_names_with_metachars_rejected() {
        let mut b = fixture(true);
        // Single-quote injection attempt — would close the TOML literal
        // and let the rest become syntax. parse_resolvers filters this.
        b.upstream_resolvers = r#"["bad'name"]"#.into();
        let err = generate(&b).unwrap_err().to_string();
        assert!(err.contains("characters outside"));
    }

    #[test]
    fn tor_proxy_line_appears_only_when_tor_enabled() {
        let mut b = fixture(true);
        b.tor_enabled = true;
        b.tor_socks_port = 9053;
        let body = generate(&b).unwrap();
        assert!(body.contains("proxy = 'socks5://127.0.0.1:9053'"));
    }

    #[test]
    fn tor_off_emits_no_proxy_line() {
        let body = generate(&fixture(true)).unwrap();
        // Belt-and-braces against a future refactor that flips the
        // default — tor MUST be off unless explicitly enabled. See
        // memory: feedback_dns_bundle.md.
        assert!(!body.contains("proxy ="));
    }

    #[test]
    fn additional_config_appended_after_baseline() {
        let mut b = fixture(true);
        b.additional_config = "log_level = 4\nuse_syslog = false".into();
        let body = generate(&b).unwrap();
        // Marker comment so operators reading the file see where the
        // freeform append starts.
        let marker_idx = body.find("--- operator-supplied additional_config ---").unwrap();
        let log_idx = body.find("log_level = 4").unwrap();
        assert!(log_idx > marker_idx);
    }

    #[test]
    fn out_of_range_port_rejected() {
        let mut b = fixture(true);
        b.listen_port = 0;
        assert!(generate(&b).is_err());
        b.listen_port = 70000;
        assert!(generate(&b).is_err());
    }

    #[test]
    fn malformed_json_resolvers_rejected() {
        let mut b = fixture(true);
        b.upstream_resolvers = "not json".into();
        assert!(generate(&b).unwrap_err().to_string().contains("not valid JSON"));
        b.upstream_resolvers = r#"{"k":"v"}"#.into();
        assert!(generate(&b).unwrap_err().to_string().contains("must be a JSON array"));
        b.upstream_resolvers = r#"[1, 2]"#.into();
        assert!(generate(&b).unwrap_err().to_string().contains("must be strings"));
    }
}
