//! Generate `torrc` from `db::DnsBundle` state, plus helpers for the
//! supervisor to discover the bundled PT binaries.
//!
//! Single-tor design (vs. Wiregate's dual-tor split for traffic + DNS):
//! we don't proxy peer traffic through tor, only dnscrypt-proxy's
//! upstream egress. So one tor instance is enough — exit-node
//! preferences from `tor_exit_nodes` and `tor_dns_exit_nodes` are
//! merged into a single `ExitNodes` directive.
//!
//! ## What we render
//!
//! - `SocksPort 127.0.0.1:<tor_socks_port>` — exposed to dnscrypt-proxy
//!   only. Loopback-bound so a misconfigured firewall can't accidentally
//!   open the SOCKS port to the internet.
//! - `DataDirectory <dns_dir>/tor` — persistent tor cache so bootstrap
//!   doesn't re-download consensus every restart.
//! - `ExitNodes` (if any), `StrictNodes 0` (don't refuse all traffic
//!   when the operator's preferred country is unreachable — fall back
//!   to any working exit).
//! - `ClientTransportPlugin <name> exec <path>` (when `tor_plugin` is
//!   set) — paths point at the extracted binaries under `<dns_dir>/bin/`.
//! - `UseBridges 1` + bridge lines (when `tor_use_bridges` is set).
//!   We don't auto-fetch from BridgeDB (Wiregate scrapes their HTTP
//!   page; that's a curl-and-pray dependency I don't want at startup).
//!   Operators paste bridge lines into `additional_config`.
//!
//! ## Bridge-fetching philosophy
//!
//! BridgeDB scraping is intentionally NOT done. Wiregate's
//! entrypoint.sh hits `bridges.torproject.org/bridges?transport=obfs4`
//! at startup, parses HTML out of the response, and pastes whatever it
//! finds into the torrc. That's:
//!
//! 1. A network call at startup (slow + brittle if BridgeDB is down)
//! 2. HTML scraping of an unstable third-party page
//! 3. No control over which bridges the operator gets
//!
//! Instead, the admin UI tells the operator "go to
//! <https://bridges.torproject.org/options>, request bridges for your
//! chosen PT, paste them into additionalConfig". One-time setup, then
//! the bridges live in our DB where they belong.

use anyhow::{anyhow, Result};
use std::path::{Path, PathBuf};

use crate::db;

/// Allowed values for `db::DnsBundle::tor_plugin`. Empty disables PTs.
/// The corresponding binary must exist in our bundle (extracted by
/// `runtime::extract_all` on startup).
pub const ALLOWED_PLUGINS: &[&str] = &["", "obfs4", "snowflake", "webtunnel"];

/// Map a `tor_plugin` name to the executable filename our runtime
/// extractor places under `<dns_dir>/bin/`. `obfs4` resolves to
/// `lyrebird` (the maintained successor of obfs4proxy) — Tor's torrc
/// still spells the transport name `obfs4`, but the binary providing
/// it changed names in 2024.
pub fn plugin_binary_name(plugin: &str) -> Option<&'static str> {
    match plugin {
        "obfs4" => Some("lyrebird"),
        // These must be the names `dns::runtime::BUNDLED` extracts into
        // `<dns_dir>/bin/`, not the upstream project's conventional binary
        // names. Tor's own docs say `snowflake-client` / `webtunnel-client`,
        // and that is what these used to return — but the extractor writes
        // `snowflake` and `webtunnel` (dns/runtime.rs:77,84), so the torrc
        // pointed `ClientTransportPlugin ... exec` at paths that never exist
        // and tor refused to start. `obfs4` worked only because `lyrebird`
        // happens to match on both sides.
        "snowflake" => Some("snowflake"),
        "webtunnel" => Some("webtunnel"),
        _ => None,
    }
}

/// Render the torrc body. Caller writes this to `<dns_dir>/torrc` and
/// passes `-f <path>` to tor.
pub fn generate(bundle: &db::DnsBundle, bin_dir: &Path) -> Result<String> {
    if !ALLOWED_PLUGINS.contains(&bundle.tor_plugin.as_str()) {
        return Err(anyhow!(
            "tor_plugin {:?} not in {:?}",
            bundle.tor_plugin,
            ALLOWED_PLUGINS
        ));
    }
    if bundle.tor_socks_port < 1 || bundle.tor_socks_port > 65535 {
        return Err(anyhow!(
            "tor_socks_port {} is out of range",
            bundle.tor_socks_port
        ));
    }

    // ExitNodes accept braced 2-letter country codes (`{us}`) or fingerprints.
    // Reject anything outside the safe charset upstream of here so
    // a malicious value can't smuggle a torrc directive through.
    validate_exit_nodes_field(&bundle.tor_exit_nodes, "tor_exit_nodes")?;
    validate_exit_nodes_field(&bundle.tor_dns_exit_nodes, "tor_dns_exit_nodes")?;
    validate_additional_config(&bundle.additional_config)?;

    let mut tor = String::new();
    tor.push_str("# Generated by coffeeblack-vpn — do NOT hand-edit; changes are\n");
    tor.push_str("# overwritten on every supervisor reconcile.\n\n");

    // SOCKS port — loopback only. dnscrypt-proxy connects here when
    // its `proxy = 'socks5://127.0.0.1:<port>'` line is enabled.
    tor.push_str(&format!(
        "SocksPort 127.0.0.1:{port} IsolateSOCKSAuth IsolateClientAddr IsolateClientProtocol IsolateDestAddr IsolateDestPort\n",
        port = bundle.tor_socks_port,
    ));

    // No control port — we never inject NEWNYM signals or query tor
    // state. Skipping the ControlPort line keeps the attack surface
    // smaller. (Wiregate uses ControlPort 9051 for circuit rotation;
    // we don't ship that feature.)

    // DataDirectory: persistent cache so bootstrap is fast across restarts.
    let data_dir = bin_dir
        .parent()
        .map(|p| p.join("tor-data"))
        .unwrap_or_else(|| PathBuf::from("/tmp/coffeeblack-vpn-tor-data"));
    tor.push_str(&format!("DataDirectory {}\n", data_dir.display()));

    // Run as the same user as the parent (don't try to setuid). Inside
    // our docker container we're already root or a dedicated UID; the
    // supervisor doesn't drop privs.
    tor.push_str("# (no `User` directive — we run as the supervisor's UID)\n");

    // Exit-node preferences. If the operator gave us a value, honour
    // it but don't make it strict — a strict policy on a small
    // preferred set can deadlock if all exits in the set are down.
    let merged_exits = merge_exit_nodes(&bundle.tor_exit_nodes, &bundle.tor_dns_exit_nodes);
    if !merged_exits.is_empty() {
        tor.push_str(&format!("ExitNodes {merged_exits}\n"));
        tor.push_str("StrictNodes 0\n");
    }

    // Pluggable transport — point at the binary path we extract on
    // startup. tor will spawn this as a managed PT subprocess and read
    // its STDOUT for the SOCKS port to forward to.
    if let Some(bin_name) = plugin_binary_name(&bundle.tor_plugin) {
        let path = bin_dir.join(bin_name);
        tor.push_str(&format!(
            "ClientTransportPlugin {plugin} exec {path}\n",
            plugin = bundle.tor_plugin,
            path = path.display(),
        ));
        // Snowflake takes extra ICE/broker arguments; without them
        // the client can't reach the snowflake broker. The defaults
        // from the upstream snowflake README work for ~99% of users.
        if bundle.tor_plugin == "snowflake" {
            tor.push_str(
                "ClientTransportPlugin snowflake exec ",
            );
            // Re-emit a single combined PT line — tor takes the LAST
            // ClientTransportPlugin entry per transport name, so this
            // overrides the bare-exec line above with the configured
            // broker / front / STUN parameters.
            tor.push_str(&format!("{}", path.display()));
            tor.push_str(
                " -url https://snowflake-broker.azureedge.net/ \
                 -front ajax.aspnetcdn.com \
                 -ice stun:stun.l.google.com:19302,stun:stun.antisip.com:3478,stun:stun.bluesip.net:3478 \
                 -log /dev/null\n",
            );
        }
    }

    // Bridges. Without bridge lines the directive is a no-op (tor
    // refuses to start, actually — `UseBridges 1` requires at least
    // one Bridge line). So we only emit `UseBridges` when both the
    // toggle is on AND there's at least one Bridge line in
    // additional_config.
    let has_bridges_in_additional = bundle
        .additional_config
        .lines()
        .any(|l| l.trim_start().to_lowercase().starts_with("bridge "));
    if bundle.tor_use_bridges {
        if !has_bridges_in_additional {
            return Err(anyhow!(
                "tor_use_bridges is true but additional_config contains no `Bridge ` lines — \
                 paste your bridge lines from https://bridges.torproject.org/options"
            ));
        }
        tor.push_str("UseBridges 1\n");
    }

    // Hardening: refuse to log anything potentially identifying. Stdout
    // goes through the supervisor's tracing pump, where filters apply.
    tor.push_str("Log notice stdout\n");
    tor.push_str("AvoidDiskWrites 1\n");

    if !bundle.additional_config.trim().is_empty() {
        tor.push_str("\n# --- operator-supplied additional_config ---\n");
        tor.push_str(bundle.additional_config.trim_end());
        tor.push('\n');
    }

    Ok(tor)
}

/// Combine the two exit-node lists. The single-tor design merges them
/// into one `ExitNodes` directive — there's no separate DNS-only tor
/// instance in our setup, so there's nowhere to apply a separate list.
/// Operators who want hard separation between query egress and content
/// egress need a different architecture (multi-tor, like Wiregate's).
fn merge_exit_nodes(a: &str, b: &str) -> String {
    let mut parts: Vec<&str> = a
        .split(',')
        .chain(b.split(','))
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .collect();
    // De-dup while preserving order. Vec::dedup wants sorted input,
    // which would change the order; use a manual scan instead.
    let mut seen = std::collections::HashSet::new();
    parts.retain(|p| seen.insert(*p));
    parts.join(",")
}

/// Validate an `ExitNodes`-shaped string. Allowed: braced 2-letter
/// country codes (`{us}`), comma-separated. Reject anything else —
/// most importantly, any byte that could let an operator inject a
/// torrc directive (newlines, hash, anything with whitespace).
fn validate_exit_nodes_field(value: &str, field_name: &str) -> Result<()> {
    let v = value.trim();
    if v.is_empty() {
        return Ok(());
    }
    for entry in v.split(',') {
        let entry = entry.trim();
        if entry.is_empty() {
            continue;
        }
        // Country codes: `{XX}` exactly. Two ASCII letters between
        // matched braces. Wiregate uses this same shape.
        if entry.starts_with('{') && entry.ends_with('}') {
            let body = &entry[1..entry.len() - 1];
            if body.len() == 2 && body.chars().all(|c| c.is_ascii_alphabetic()) {
                continue;
            }
        }
        // Fingerprints — 40 uppercase hex chars optionally prefixed `$`.
        let hex = entry.strip_prefix('$').unwrap_or(entry);
        if hex.len() == 40 && hex.chars().all(|c| c.is_ascii_hexdigit()) {
            continue;
        }
        return Err(anyhow!(
            "{field_name}: entry {entry:?} is not a valid country code ({{XX}}) \
             or 40-char fingerprint"
        ));
    }
    Ok(())
}

/// Reject torrc directives in operator-supplied `additional_config` that would
/// make tor execute an arbitrary program (as root, given the parent process).
/// tor treats several directives as "run this binary": `ClientTransportPlugin`
/// / `ServerTransportPlugin … exec …`, `__OwningControllerProcess`, and any
/// `exec` token. Pluggable transports the app itself needs are emitted from the
/// validated `tor_plugin` field into the baseline config — never from this
/// free-form field — so blocking them here costs the operator nothing.
fn validate_additional_config(value: &str) -> Result<()> {
    for raw in value.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let lower = line.to_ascii_lowercase();
        let first = lower.split_whitespace().next().unwrap_or("");
        const BLOCKED: &[&str] = &[
            "clienttransportplugin",
            "servertransportplugin",
            "__owningcontrollerprocess",
            "owningcontrollerprocess",
            "controlportwritetofile",
            "hashedcontrolpassword",
            "extorport",
        ];
        if BLOCKED.contains(&first) || lower.split_whitespace().any(|t| t == "exec") {
            return Err(anyhow!(
                "additional_config: directive {line:?} is not allowed — it can make \
                 tor execute an arbitrary program or open a control channel. Use the \
                 dedicated pluggable-transport setting instead."
            ));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn additional_config_blocks_exec_directives() {
        // Legitimate tuning lines are accepted.
        assert!(validate_additional_config("ConnectionPadding 1\nReducedConnectionPadding 0").is_ok());
        assert!(validate_additional_config("# a comment\nBridge obfs4 1.2.3.4:443 cert=x").is_ok());
        // Anything that makes tor run a program / open a control channel is rejected.
        for bad in [
            "ClientTransportPlugin obfs4 exec /bin/sh",
            "ServerTransportPlugin obfs4 exec /tmp/x",
            "__OwningControllerProcess 1234",
            "ControlPortWriteToFile /tmp/cp",
            "HashedControlPassword 16:AAAA",
            "SomeDirective foo exec bar",
        ] {
            assert!(validate_additional_config(bad).is_err(), "must reject {bad:?}");
        }
    }

    fn fixture() -> db::DnsBundle {
        db::DnsBundle {
            id: "dns0".into(),
            enabled: true,
            listen_port: 5353,
            upstream_resolvers: "[]".into(),
            require_dnssec: true,
            require_nolog: true,
            require_nofilter: false,
            tor_enabled: true,
            tor_socks_port: 9053,
            tor_exit_nodes: String::new(),
            tor_dns_exit_nodes: String::new(),
            tor_use_bridges: false,
            tor_plugin: String::new(),
            additional_config: String::new(),
            created_at: "now".into(),
            updated_at: "now".into(),
        }
    }

    fn bin_dir() -> PathBuf {
        PathBuf::from("/var/lib/coffeeblack/dns/bin")
    }

    #[test]
    fn baseline_torrc_emits_socks_and_data_dir() {
        let body = generate(&fixture(), &bin_dir()).unwrap();
        assert!(body.contains("SocksPort 127.0.0.1:9053"));
        assert!(body.contains("IsolateSOCKSAuth IsolateClientAddr"));
        assert!(body.contains("DataDirectory /var/lib/coffeeblack/dns/tor-data"));
        assert!(body.contains("AvoidDiskWrites 1"));
        // No PT or bridges in the default fixture.
        assert!(!body.contains("ClientTransportPlugin"));
        assert!(!body.contains("UseBridges"));
    }

    #[test]
    fn obfs4_plugin_resolves_to_lyrebird_path() {
        let mut b = fixture();
        b.tor_plugin = "obfs4".into();
        let body = generate(&b, &bin_dir()).unwrap();
        // The transport name in torrc is `obfs4`, but the executable
        // is `lyrebird` — operators reading the file should see this
        // explicitly so the rename isn't a surprise.
        assert!(body.contains(
            "ClientTransportPlugin obfs4 exec /var/lib/coffeeblack/dns/bin/lyrebird"
        ));
    }

    #[test]
    fn snowflake_plugin_includes_broker_args() {
        let mut b = fixture();
        b.tor_plugin = "snowflake".into();
        let body = generate(&b, &bin_dir()).unwrap();
        assert!(body.contains("snowflake-broker.azureedge.net"));
        assert!(body.contains("ajax.aspnetcdn.com"));
        assert!(body.contains("stun:stun.l.google.com:19302"));
    }

    #[test]
    fn webtunnel_plugin_uses_the_binary_the_extractor_writes() {
        let mut b = fixture();
        b.tor_plugin = "webtunnel".into();
        let body = generate(&b, &bin_dir()).unwrap();
        assert!(body.contains(
            "ClientTransportPlugin webtunnel exec /var/lib/coffeeblack/dns/bin/webtunnel"
        ), "torrc must point at the extracted filename:\n{body}");
    }

    #[test]
    fn unknown_plugin_rejected() {
        let mut b = fixture();
        b.tor_plugin = "shadowsocks".into();
        let err = generate(&b, &bin_dir()).unwrap_err().to_string();
        assert!(err.contains("not in"));
    }

    #[test]
    fn out_of_range_socks_port_rejected() {
        let mut b = fixture();
        b.tor_socks_port = 0;
        assert!(generate(&b, &bin_dir()).is_err());
        b.tor_socks_port = 100_000;
        assert!(generate(&b, &bin_dir()).is_err());
    }

    #[test]
    fn exit_nodes_country_code_accepted() {
        let mut b = fixture();
        b.tor_exit_nodes = "{us},{gb},{de}".into();
        let body = generate(&b, &bin_dir()).unwrap();
        assert!(body.contains("ExitNodes {us},{gb},{de}"));
        assert!(body.contains("StrictNodes 0"));
    }

    #[test]
    fn exit_nodes_fingerprint_accepted() {
        let mut b = fixture();
        // 40-char hex, with and without `$` prefix.
        b.tor_exit_nodes =
            "$1234567890ABCDEF1234567890ABCDEF12345678,abcdef1234567890abcdef1234567890abcdef12"
                .into();
        let body = generate(&b, &bin_dir()).unwrap();
        assert!(body.contains("ExitNodes $1234567890ABCDEF"));
    }

    #[test]
    fn exit_nodes_dedup_and_merge() {
        let mut b = fixture();
        b.tor_exit_nodes = "{us},{gb}".into();
        b.tor_dns_exit_nodes = "{us},{de}".into();
        let body = generate(&b, &bin_dir()).unwrap();
        // {us} appears in both; should only show once. Order: tor_exit
        // first, then unseen entries from tor_dns_exit.
        assert!(body.contains("ExitNodes {us},{gb},{de}"));
    }

    #[test]
    fn exit_nodes_with_metachars_rejected() {
        let mut b = fixture();
        // Newline injection — would close the ExitNodes line and let
        // the next part be a new directive.
        b.tor_exit_nodes = "{us}\nUseBridges 1".into();
        assert!(generate(&b, &bin_dir()).is_err());
        // Hash-comment injection.
        b.tor_exit_nodes = "{us} # malicious".into();
        assert!(generate(&b, &bin_dir()).is_err());
        // Wrong-case country code length.
        b.tor_exit_nodes = "{usa}".into();
        assert!(generate(&b, &bin_dir()).is_err());
        // Wrong fingerprint length.
        b.tor_exit_nodes = "deadbeef".into();
        assert!(generate(&b, &bin_dir()).is_err());
    }

    #[test]
    fn use_bridges_without_bridge_lines_rejected() {
        let mut b = fixture();
        b.tor_use_bridges = true;
        // additional_config is empty — no Bridge lines.
        let err = generate(&b, &bin_dir()).unwrap_err().to_string();
        assert!(err.contains("Bridge"));
    }

    #[test]
    fn use_bridges_with_bridge_lines_succeeds() {
        let mut b = fixture();
        b.tor_use_bridges = true;
        b.additional_config = "Bridge obfs4 192.0.2.1:443 cert=AAAA iat-mode=0".into();
        let body = generate(&b, &bin_dir()).unwrap();
        assert!(body.contains("UseBridges 1"));
        assert!(body.contains("Bridge obfs4 192.0.2.1:443"));
    }

    #[test]
    fn additional_config_appended_after_baseline() {
        let mut b = fixture();
        b.additional_config = "ConnectionPadding 1\nReducedConnectionPadding 0".into();
        let body = generate(&b, &bin_dir()).unwrap();
        let marker_idx = body.find("--- operator-supplied additional_config ---").unwrap();
        let cp_idx = body.find("ConnectionPadding 1").unwrap();
        assert!(cp_idx > marker_idx);
    }

    #[test]
    fn plugin_binary_name_maps_correctly() {
        assert_eq!(plugin_binary_name("obfs4"), Some("lyrebird"));
        assert_eq!(plugin_binary_name("snowflake"), Some("snowflake"));
        assert_eq!(plugin_binary_name("webtunnel"), Some("webtunnel"));
        assert_eq!(plugin_binary_name(""), None);
        assert_eq!(plugin_binary_name("unknown"), None);
    }

    /// The name in the torrc and the name the extractor writes to disk are
    /// set in two different modules, and when they disagreed tor simply
    /// refused to start — the pluggable transport an at-risk user selected
    /// silently did not run. Assert the invariant rather than either literal,
    /// so a rename on one side cannot drift from the other again.
    #[test]
    fn every_plugin_binary_is_one_the_extractor_actually_extracts() {
        let extracted: Vec<&str> = crate::dns::runtime::BINARIES
            .iter()
            .map(|b| b.name)
            .collect();
        for plugin in ALLOWED_PLUGINS {
            if let Some(bin) = plugin_binary_name(plugin) {
                assert!(
                    extracted.contains(&bin),
                    "torrc for {plugin:?} points at {bin:?}, which the extractor \
                     never writes (it writes {extracted:?})"
                );
            }
        }
    }
}
